### ISSUE TITLE
LSP crashes on unsaved files.

### ISSUE THREAD

**Issue by deathaxe** [tomv564/LSP#141]
1. Open a new file.
2. Set Syntax to one of the supported ones.
3. Paste some code.
4. Move mouse over keywords.

```
Traceback (most recent call last):
  File "C:\Apps\Sublime\sublime_plugin.py", line 625, in on_hover
    vel.on_hover(point, hover_zone)
  File "C:\Apps\Sublime\Data\Packages\LSP\main.py", line 1924, in on_hover
    self.request_symbol_hover(point)
  File "C:\Apps\Sublime\Data\Packages\LSP\main.py", line 1934, in request_symbol_hover
    Request.hover(get_document_position(self.view, point)),
  File "C:\Apps\Sublime\Data\Packages\LSP\main.py", line 1880, in get_document_position
    d['textDocument'] = {"uri": filename_to_uri(view.file_name())}
  File "C:\Apps\Sublime\Data\Packages\LSP\main.py", line 885, in filename_to_uri
    return urljoin('file:', pathname2url(path))
  File "./python3.3/nturl2path.py", line 46, in pathname2url
TypeError: argument of type 'NoneType' is not iterable
```

Another situation is closing an unsaved file, which creates following traceback:

```
Traceback (most recent call last):
  File "C:\Apps\Sublime\sublime_plugin.py", line 389, in run_callback
    expr()
  File "C:\Apps\Sublime\sublime_plugin.py", line 452, in <lambda>
    run_callback('on_close', callback, lambda: callback.on_close(v))
  File "C:\Apps\Sublime\Data\Packages\LSP\main.py", line 2460, in on_close
    Events.publish("view.on_close", view)
  File "C:\Apps\Sublime\Data\Packages\LSP\main.py", line 1908, in publish
    listener(*args)
  File "C:\Apps\Sublime\Data\Packages\LSP\main.py", line 1684, in remove_diagnostics
    if not window.find_open_file(view.file_name()):
  File "C:\Apps\Sublime\sublime.py", line 315, in find_open_file
    view_id = sublime_api.window_find_open_file(self.window_id, fname)
TypeError: String required
```

**Comment by tomv564** [comment]
I would like get mypy to a point where it picks up all these `TypeError`s where `view.file_name()` can be None. I welcome a fix but may take a stab at this one myself now.

**Comment by deathaxe** [comment]
> I would like get mypy to a point where it picks up all these TypeErrors where view.file_name() can be None.

This is a runtime error, which a static code analyzes tool won't be able to catch. `view.file_name()` is a valid argument. How should mypy find a situation, such a function returns `None`?

This kind of issue can only be catched by proper checks or try catch clauses in the code.

**Comment by tomv564** [comment]
Okay, by "pick up all these TypeErrors" I mean "detect all the places where the result of `view.file_name()` is not being checked, potentially resulting in TypeErrors" :)
