### ISSUE TITLE
LSP crashes, if a python file is compared with clipboard using Sublimerge 3

### ISSUE THREAD

**Issue by deathaxe** [tomv564/LSP#195]
```
Traceback (most recent call last):
  File "C:\Apps\Sublime\sublime_plugin.py", line 417, in run_async_view_listener_callback
    vel.__class__.__dict__[name](vel)
  File "C:\Apps\Sublime\Data\Packages\LSP\plugin\diagnostics.py", line 188, in on_selection_modified_async
    pos = self.view.sel()[0].begin()
  File "C:\Apps\Sublime\sublime.py", line 649, in __getitem__
    raise IndexError()
IndexError
```

**Comment by tomv564** [comment]
Thanks for reporting, should be fixed in https://github.com/tomv564/LSP/commit/726739b8f51889ccafcbcb5cde520d0d9d2364f1
