### ISSUE TITLE
Wait for loading the environment before starting the servers

### ISSUE THREAD

**Issue by golddranks** [tomv564/LSP#204]
At the moment I sometimes get logs like this:
```
LSP: starting ['rustup', 'run', 'nightly', 'rls']
Failed to start server
Traceback (most recent call last):
  File "plugin.core.main in /Users/kon/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package", line 253, in start_server
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'rustup'

LSP: Could not start ['rustup', 'run', 'nightly', 'rls'] , disabling
environment variables loaded using: /usr/local/bin/fish -l
Package Control: Skipping automatic upgrade, last run at 2017-11-17 03:39:51, next run at 2017-11-17 04:39:51 or after
LSP: Couldn't determine project directory since no folders are open! Using /Users/kon/my_rust/visu/src as a fallback.
LSP: starting in /Users/kon/my_rust/visu/src
LSP: starting ['rustup', 'run', 'nightly', 'rls']
LSP:  --> initialize
DEBUG:rls::server: Language Server starting up. Version: 0.123.0-nightly (015073b 2017-11-10):
```
It eventually manages to start the server, so nothing fatal here. But it might be good if it waited for the environment before trying to start the server – here it clearly fails because the commands aren't in the PATH before loading the environment.

**Comment by rwols** [comment]
See: https://github.com/SublimeTextIssues/Core/issues/1877

**Comment by tomv564** [comment]
Closing because duplicate, but taking a mental note to revisit the linked issue soon.
