### ISSUE TITLE
Error with folder open and pasting code to new tab

### ISSUE THREAD

**Issue by buildersbrewery** [tomv564/LSP#219]
* I had a folder opened in Sublime.
* Then opened a new tab to paste some code to it.

---

Got the following error in the Sublime console:

```text
Traceback (most recent call last):
  File "..\sublime3\sublime_plugin.py", line 389, in run_callback
    expr()
  File "..\sublime3\sublime_plugin.py", line 456, in <lambda>
    run_callback('on_close', callback, lambda: callback.on_close(v))
  File "plugin.core.documents in ..\sublime3\Data\Installed Packages\LSP.sublime-package", line 204, in on_close
  File "plugin.core.events in ..\sublime3\Data\Installed Packages\LSP.sublime-package", line 28, in publish
  File "plugin.core.diagnostics in ..\sublime3\Data\Installed Packages\LSP.sublime-package", line 71, in remove_diagnostics
  File "plugin.core.events in ..\sublime3\Data\Installed Packages\LSP.sublime-package", line 28, in publish
  File "plugin.diagnostics in ..\sublime3\Data\Installed Packages\LSP.sublime-package", line 166, in <lambda>
  File "plugin.diagnostics in ..\sublime3\Data\Installed Packages\LSP.sublime-package", line 174, in handle_diagnostics
  File "plugin.diagnostics in ..\sublime3\Data\Installed Packages\LSP.sublime-package", line 231, in update_diagnostics_panel
  File "plugin.core.workspace in ..\sublime3\Data\Installed Packages\LSP.sublime-package", line 20, in get_project_path
AttributeError: 'NoneType' object has no attribute 'file_name'
```

---

* Sublime Text Build 3156 portable x64
* LSP package `v0.4.1`
* Win10 Pro x64 1709

**Comment by rwols** [comment]
I cannot reproduce this. Do you have more detailed instructions on how to reproduce this?

The stack trace seems to suggest that `window.active_view()` is `None` [here](https://github.com/tomv564/LSP/blob/master/plugin/core/workspace.py#L20).

**Comment by buildersbrewery** [comment]
That could've been the case as I was switching back and forth between windows (of Sublime and other applications).

I'm trying to write down a more detailed step-by-step guide. But there's nothing that's consistent enough to post for now. Will post as soon as I have it.

**Comment by tomv564** [comment]
Thanks for the troubleshooting, I added a check for the error @rwols spotted in commit 0133bae74cae38ff7f277f247fcb7be0ee8492c3

**Comment by buildersbrewery** [comment]
Will close for now.
