### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by evandrocoan** [tomv564/LSP#243]
I just tried to run the command show document symbols and got this:
```
LSP:  --> textDocument/documentSymbol
Error handling server payload
Traceback (most recent call last):
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\rpc.py", line 133, in read_stdout
    self.response_handler(payload)
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\rpc.py", line 178, in response_handler
    self._response_handlers[handler_id](result)
  File "F:\SublimeText\Data\Packages\LSP\plugin\symbols.py", line 59, in handle_response
    symbols = list(format_symbol(item) for item in response)
  File "F:\SublimeText\Data\Packages\LSP\plugin\symbols.py", line 59, in <genexpr>
    symbols = list(format_symbol(item) for item in response)
  File "F:\SublimeText\Data\Packages\LSP\plugin\symbols.py", line 35, in format_symbol
    prefix = item["containerName"] + "." if "containerName" in item else ""
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

```
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\>python --version
Python 3.6.3 :: Anaconda, Inc.

C:\>pip show jedi
Name: jedi
Version: 0.11.1
Summary: An autocompletion tool for Python that can be used for text editors.
Home-page: https://github.com/davidhalter/jedi
Author: David Halter
Author-email: davidhalter88@gmail.com
License: MIT
Location: f:\python\lib\site-packages
Requires: parso

C:\>pip show python-language-server
Name: python-language-server
Version: 0.12.2
Summary: Python Language Server for the Language Server Protocol
Home-page: https://github.com/palantir/python-language-server
Author: Palantir Technologies, Inc.
Author-email: UNKNOWN
License: UNKNOWN
Location: f:\python\lib\site-packages
Requires: rope, mccabe, pyflakes, future, pydocstyle, yapf, pycodestyle, json-rpc, pluggy, jedi, configparser

C:\>
```

**Comment by tomv564** [comment]
I certainly didn't test this feature against `pyls`, will give it a try shortly. Thanks for reporting!

**Comment by tomv564** [comment]
I closed this bug for now, but please continue to give feedback about the document symbols feature. I'm sure there's a use for it, but for now pyls just returns an unfiltered list of _all_ symbols.
