### ISSUE TITLE
ValueError: path is on mount 'D:', start on mount 'F:'

### ISSUE THREAD

**Issue by evandrocoan** [tomv564/LSP#247]
My project is on disk F, but I opened a external file on disk D and used the command `Find References`:
```
LSP:  --> textDocument/references
Error handling server payload
Traceback (most recent call last):
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\rpc.py", line 133, in read_stdout
    self.response_handler(payload)
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\rpc.py", line 178, in response_handler
    self._response_handlers[handler_id](result)
  File "F:\SublimeText\Data\Packages\LSP\plugin\references.py", line 51, in <lambda>
    request, lambda response: self.handle_response(response, pos))
  File "F:\SublimeText\Data\Packages\LSP\plugin\references.py", line 58, in handle_response
    relative_file_path = os.path.relpath(file_path, base_dir) if base_dir else file_path
  File "./python3.3/ntpath.py", line 564, in relpath
ValueError: path is on mount 'D:', start on mount 'F:'
```

**Comment by tomv564** [comment]
Added a fix for this, but in general errors are to be expected when invoking operations on files outside the current workspace.
