### ISSUE TITLE
TypeError: can't concat bytes to str

### ISSUE THREAD

**Issue by evandrocoan** [tomv564/LSP#249]
I am not sure how to reproduce, but I have enabled debug and this popped some time after:
```
:
2018-01-20 23:03:54,977 parso.python.diff diff parser start:
2018-01-20 23:03:54,978 parso.python.diff diff parser calculated:
2018-01-20 23:03:54,979 parso.python.diff diff: line_lengths old: 66, new: 66:
2018-01-20 23:03:54,979 parso.python.diff diff equal old[1:32] new[1:32]:
2018-01-20 23:03:54,980 parso.python.diff diff actually copy 1 to 7:
2018-01-20 23:03:55,013 parso.python.diff parse_part from 8 to 33 (to 33 in part parser):
2018-01-20 23:03:55,013 parso.python.diff diff replace old[33:33] new[33:33]:
2018-01-20 23:03:55,014 parso.python.diff diff equal old[34:66] new[34:66]:
2018-01-20 23:03:55,016 parso.python.diff parse_part from 34 to 34 (to 34 in part parser):
2018-01-20 23:03:55,017 parso.python.diff diff actually copy 35 to 65:
2018-01-20 23:03:55,018 parso.python.diff diff parser end:
2018-01-20 23:03:55,219 parso.cache pickle loaded: d:\user\dropbox\softwareversioning\pycodestyle\pycodestyle.py:
2018-01-20 23:03:55,289 pyls.config.config   finish pyls_hover --> [hook]:
Exception in thread Thread-112:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\rpc.py", line 164, in read_stderr
    server_log(decoded.strip())
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\logging.py", line 18, in server_log
    printf(*args, prefix=binary)
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\logging.py", line 23, in printf
    print(prefix + ":", *args)
TypeError: can't concat bytes to str
```

Perhaps use `print(prefix + ":", str(*args))` so we can know what it was trying to print?

**Comment by tomv564** [comment]
Are you able to make this change locally in hopes of trapping the error?

**Comment by evandrocoan** [comment]
Sure, I shall put a try...catch for the exception then print like 10 `\n` new lines to make sure I see it.

While writing it https://github.com/evandroforks/LSP/commit/a20f6c95a70d383a01043e435563811d9393f3b7, the only why to make it work was like this:
```
File: Data/Packages/LSP/plugin/core/logging.py
21: def printf(*args, prefix=PLUGIN_NAME):
22:     """Print args to the console, prefixed by the plugin name."""
23:     try:
24:         print(prefix + ":", *args)
25: 
26:     except:
27:         sys.stderr.write("\n"*10)
28:         print(prefix + ":", str(args))
29: 
30:         with open("D:/User/Downloads/LSP_issues_249.txt", "a", newline='\n') as text_file:
31:             text_file.write(prefix + ":" + str(args)+"\n")
32: 
```

**Comment by evandrocoan** [comment]
It happened again, but doing `str()` on the try catch did not worked:
```
Exception in thread Thread-63:
Traceback (most recent call last):
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\logging.py", line 24, in printf
    print(prefix + ":", *args)
TypeError: can't concat bytes to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\rpc.py", line 164, in read_stderr
    server_log(decoded.strip())
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\logging.py", line 18, in server_log
    printf(*args, prefix=binary)
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\logging.py", line 28, in printf
    print(prefix + ":", str(args))
TypeError: can't concat bytes to str
```

**Comment by evandrocoan** [comment]
@tomv564, I am trying this now:
```python
File: Data/Packages/LSP/plugin/core/logging.py
21: def printf(*args, prefix=PLUGIN_NAME):
22:     """Print args to the console, prefixed by the plugin name."""
23:     try:
24:         print(prefix + ":", *args)
25: 
26:     except Exception as error:
27:         sys.stderr.write("\n"*10)
28:         print(str(prefix))
29:         print(":")
30:         print(str(args))
31: 
32:         with open("D:/User/Downloads/LSP_issues_249.txt", "a", newline='\n') as text_file:
33:             text_file.write(str(prefix))
34:             text_file.write(":")
35:             text_file.write("\n")
36:             text_file.write(str(args))
37:             text_file.write(", Exception: ")
38:             text_file.write("\n")
39:             text_file.write(str(error))
40:             text_file.write("\n")
```

What do you think, still missing something?

**Comment by evandrocoan** [comment]
This last function worked, when the bug happened. This are the contents of the file `LSP_issues_249.txt`:
```
b'filename\xa0\xa0Specifies that a FileHandler be created, using the specified':
(), Exception: 
can't concat bytes to str
b'\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0filename, rather than a StreamHandler.':
(), Exception: 
can't concat bytes to str
b'filemode\xa0\xa0Specifies the mode to open the file, if filename is specified':
(), Exception: 
can't concat bytes to str
b"\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0(if filemode is unspecified, it defaults to 'a').":
(), Exception: 
can't concat bytes to str
b'format\xa0\xa0\xa0\xa0Use the specified format string for the handler.':
(), Exception: 
can't concat bytes to str
b'datefmt\xa0\xa0 Use the specified date/time format.':
(), Exception: 
can't concat bytes to str
b'style\xa0\xa0\xa0\xa0 If a format string is specified, use this to specify the':
(), Exception: 
can't concat bytes to str
b"\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0type of format string (possible values '%', '{', '$', for":
(), Exception: 
can't concat bytes to str
b'\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0%-formatting, :meth:`str.format` and :class:`string.Template`':
(), Exception: 
can't concat bytes to str
b"\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0- defaults to '%').":
(), Exception: 
can't concat bytes to str
b'level\xa0\xa0\xa0\xa0 Set the root logger level to the specified level.':
(), Exception: 
can't concat bytes to str
b'stream\xa0\xa0\xa0\xa0Use the specified stream to initialize the StreamHandler. Note':
(), Exception: 
can't concat bytes to str
b"\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0that this argument is incompatible with 'filename' - if both":
(), Exception: 
can't concat bytes to str
b"\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0are present, 'stream' is ignored.":
(), Exception: 
can't concat bytes to str
b'handlers\xa0\xa0If specified, this should be an iterable of already created':
(), Exception: 
can't concat bytes to str
b'\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0handlers, which will be added to the root handler. Any handler':
(), Exception: 
can't concat bytes to str
b'\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0in the list which does not have a formatter assigned will be':
(), Exception: 
can't concat bytes to str
b'\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0assigned the formatter created in this function.':
(), Exception: 
can't concat bytes to str
b'\xa0\xa0 Added the ``style`` parameter.':
(), Exception: 
can't concat bytes to str
b'\xa0\xa0 Added the ``handlers`` parameter. A ``ValueError`` is now thrown for':
(), Exception: 
can't concat bytes to str
b'\xa0\xa0 incompatible arguments (e.g. ``handlers`` specified together with':
(), Exception: 
can't concat bytes to str
b'\xa0\xa0 ``filename``/``filemode``, or ``filename``/``filemode`` specified':
(), Exception: 
can't concat bytes to str
b'\xa0\xa0 together with ``stream``, or ``handlers`` specified together with':
(), Exception: 
can't concat bytes to str
b'\xa0\xa0 ``stream``.':
(), Exception: 
can't concat bytes to str
```

**Comment by evandrocoan** [comment]
It happened around the time of these exceptions on the other issue  https://github.com/tomv564/LSP/issues/250#issuecomment-359630045

**Comment by tomv564** [comment]
I changed `server_log`, can you try again?

You shouldn't be seeing `bytes` in server_log, but another user has reported UnicodeDecodeError in `read_stderr` in rpc.py before, which falls back to passing bytes in to `server_log`. If the issue continues after updating your fork, perhaps you can adding logging in the `except` handler to see what content fails to be decoded?

**Comment by evandrocoan** [comment]
>  If the issue continues after updating your fork, perhaps you can adding logging in the except handler to see what content fails to be decoded

I already had added log on the except handler on https://github.com/tomv564/LSP/issues/249#issuecomment-359627360, these were the contents it had tried to print when it throwed the exception https://github.com/tomv564/LSP/issues/249#issuecomment-359630496

**Comment by evandrocoan** [comment]
They are parts of some of my source code files I had opened on Sublime Text. I am not sure why they are being printed there. But they also have some stranger stuff like these `b'\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0filename, ...`

**Comment by tomv564** [comment]
Did you encounter this issue with the updated `server_log` ?

The stranger stuff might be pyls logging your document contents in eg didChange over stderr.

**Comment by evandrocoan** [comment]
Thanks! I tried to reproduce it by killing the server, restarting it, reloading LSP package, but none of it could do. I think that after https://github.com/tomv564/LSP/commit/e5ae5c814b425b75c6576d211f7470c709c485a0 *(Include OSError in exception handler when writing)* and https://github.com/tomv564/LSP/commit/819b968a3bb73c1e8fed1a9c5440c8122a6dec9e *(Replace binary argument with hardcoded text "server")* this should not happen anymore, but I will let the logging code on my fork:
```python
26:     except Exception as error:
27:         ...
32:         with open("D:/User/Downloads/LSP_issues_249.txt", "a", newline='\n') as text_file:
33:             text_file.write(str(prefix))
34:             ...
```
Then if this happens again, it will create the file `LSP_issues_249.txt` on my `Downloads` folder with the contents of the error. Therefore, I am closing this while I wait for it. If someday that file is created then I reopen this issue with the contents of that file.

**Comment by AmjadHD** [comment]
it happens with typescript-languageserver:
log:
```
LSP: starting ['typescript-language-server.cmd', '--stdio']
LSP:  --> initialize
LSP: window 2 added session typescript-language-server
Exception in thread Thread-5:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\LSP\plugin\core\process.py", line 78, in log_stream
    server_log(decoded.strip())
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\LSP\plugin\core\logging.py", line 44, in server_log
    printf(*args, prefix=server_name)
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\LSP\plugin\core\logging.py", line 49, in printf
    print(prefix + ":", *args)
TypeError: can't concat bytes to str
```

**Comment by tomv564** [comment]
@AmjadHD, can you wrap a try-catch around the `print` call with the same logging  as evandrocoan had? Is it a reliable repro?

**Comment by AmjadHD** [comment]
I added this:
```diff
diff --git a/plugin/core/process.py b/plugin/core/process.py
index da0122c..c920d2f 100644
--- a/plugin/core/process.py
+++ b/plugin/core/process.py
@@ -72,8 +72,11 @@ def log_stream(process: 'subprocess.Popen', stream: 'IO[Any]') -> None:
                 break
             try:
                 decoded = content.decode("UTF-8")
-            except UnicodeDecodeError:
+            except UnicodeDecodeError as err:
                 # todo: do we still need this ?
+                print("==========START_ERROR=============")
+                print(err, "\ncontent:", content)
+                print("==========END_ERROR=============")
                 decoded = content  # type: ignore
             server_log(decoded.strip())
         except IOError as err:
```
and I got this:
==========START_ERROR=============
'utf-8' codec can't decode byte 0xff in position 11: invalid start byte 
content: b'Information\xff: impossible de trouver des fichiers pour le(s) mod\x8ale(s) sp\x82cifi\x82(s).\r\n'
==========END_ERROR=============
It's a decoding error, my system's language is french, some of it's characters are not utf-8 (e.g é, è, ...)

**Comment by rwols** [comment]
@AmjadHD could you try changing `UTF-8` to `UTF-16` at the following lines and see if the error persists?

https://github.com/tomv564/LSP/blob/24ffd7f49130e41aecf76715ee78dd55696702df/plugin/core/transports.py#L143

https://github.com/tomv564/LSP/blob/24ffd7f49130e41aecf76715ee78dd55696702df/plugin/core/transports.py#L160

https://github.com/tomv564/LSP/blob/24ffd7f49130e41aecf76715ee78dd55696702df/plugin/core/transports.py#L213

https://github.com/tomv564/LSP/blob/24ffd7f49130e41aecf76715ee78dd55696702df/plugin/core/transports.py#L240

**Comment by AmjadHD** [comment]
that fixed it

**Comment by rwols** [comment]
Hmm, after looking at the spec I think the ones in transport.py need to be UTF-8, but I'm not sure about the one in process.py.

**Comment by rwols** [comment]
So the one in process.py is just reading stderr. There's nothing in the specification about that. I guess it depends on the server what encoding it is using. I would expect any server to be using UTF-8.

**Comment by tomv564** [comment]
It feels like the bytes are already un-decodable before we `readline()` them:

Detecting:
```python
>>> import chardet
>>> chardet.detect(b'Information\xff: impossible de trouver des fichiers pour le(s) mod\x8ale(s) sp\x82cifi\x82(s).\r\n')
{'encoding': 'Windows-1252', 'confidence': 0.5334615384615384, 'language': ''}
```
Decoding:
```python
>>> b'Information\xff: impossible de trouver des fichiers pour le(s) mod\x8ale(s) sp\x82cifi\x82(s).\r\n'.decode('windows-1252')
'Informationÿ: impossible de trouver des fichiers pour le(s) modŠle(s) sp‚cifi‚(s).\r\n'
```

One could  a batch file or node script that print the correct content and test how the output looks with `subprocess.check_output`.

But given that this is for debugging purposes, perhaps a lossy solution is acceptable.

**Comment by rwols** [comment]
@evandrocoan @AmjadHD undecodeable UTF-8 sequences should now be replaced by question marks (https://github.com/tomv564/LSP/pull/803).
