### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by evandrocoan** [tomv564/LSP#256]
While running into:

1. https://github.com/tomv564/LSP/issues/250 OSError: [Errno 22] Invalid argument

It showed something new, when I saved a file:
```
reloading settings Packages/User/BufferScroll.sublime-settings
Traceback (most recent call last):
  File "F:\SublimeText\sublime_plugin.py", line 280, in <lambda>
    lambda: check_view_event_listeners(view))
  File "F:\SublimeText\sublime_plugin.py", line 267, in check_view_event_listeners
    want = is_view_event_listener_applicable(cls, view)
  File "F:\SublimeText\sublime_plugin.py", line 232, in is_view_event_listener_applicable
    if not cls.is_applicable(view.settings()):
  File "F:\SublimeText\Data\Packages\LSP\plugin\completion.py", line 139, in is_applicable
    return is_supported_syntax(syntax)
TypeError: 'NoneType' object is not callable
```

And
```
Traceback (most recent call last):
  File "F:\SublimeText\sublime_plugin.py", line 654, in on_text_command
    res = callback.on_text_command(v, name, args)
  File "F:\SublimeText\Data\Packages\LSP\plugin\completion.py", line 74, in on_text_command
    if settings.resolve_completion_for_snippets and current_completion:
AttributeError: 'NoneType' object has no attribute 'resolve_completion_for_snippets'
Traceback (most recent call last):
  File "F:\SublimeText\sublime_plugin.py", line 389, in run_callback
    expr()
  File "F:\SublimeText\sublime_plugin.py", line 496, in <lambda>
    run_callback('on_modified', callback, lambda: callback.on_modified(v))
  File "F:\SublimeText\Data\Packages\LSP\plugin\completion.py", line 80, in on_modified
    if settings.resolve_completion_for_snippets and view.file_name():
AttributeError: 'NoneType' object has no attribute 'resolve_completion_for_snippets'
```

<details>
<p>

```
LSP:  --> textDocument/didChange
Traceback (most recent call last):
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\documents.py", line 110, in <lambda>
    lambda: purge_did_change(buffer_id, buffer_version), 500)
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\documents.py", line 121, in purge_did_change
    notify_did_change(pending_buffer["view"])
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\documents.py", line 195, in notify_did_change
    client.send_notification(Notification.didChange(params))
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\rpc.py", line 63, in send_notification
    self.send_payload(notification.to_payload())
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\rpc.py", line 85, in send_payload
    self.process.stdin.write(bytes(message, 'UTF-8'))
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "F:\SublimeText\sublime_plugin.py", line 654, in on_text_command
    res = callback.on_text_command(v, name, args)
  File "F:\SublimeText\Data\Packages\LSP\plugin\completion.py", line 74, in on_text_command
    if settings.resolve_completion_for_snippets and current_completion:
AttributeError: 'NoneType' object has no attribute 'resolve_completion_for_snippets'
Traceback (most recent call last):
  File "F:\SublimeText\sublime_plugin.py", line 417, in run_async_view_listener_callback
    vel.__class__.__dict__[name](vel)
  File "F:\SublimeText\Data\Packages\LSP\plugin\diagnostics.py", line 191, in on_selection_modified_async
    line_diagnostics = get_line_diagnostics(self.view, pos)
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "F:\SublimeText\sublime_plugin.py", line 417, in run_async_view_listener_callback
    vel.__class__.__dict__[name](vel)
  File "F:\SublimeText\Data\Packages\LSP\plugin\diagnostics.py", line 191, in on_selection_modified_async
    line_diagnostics = get_line_diagnostics(self.view, pos)
TypeError: 'NoneType' object is not callable
LSP:  --> textDocument/didSave
Traceback (most recent call last):
  File "F:\SublimeText\sublime_plugin.py", line 487, in on_post_save_async
    callback.on_post_save_async(v)
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\documents.py", line 211, in on_post_save_async
    Events.publish("view.on_post_save_async", view)
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\events.py", line 28, in publish
    listener(*args)
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\documents.py", line 169, in notify_did_save
    client.send_notification(Notification.didSave(params))
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\rpc.py", line 63, in send_notification
    self.send_payload(notification.to_payload())
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\rpc.py", line 86, in send_payload
    self.process.stdin.flush()
OSError: [Errno 22] Invalid argument
Unhandled exception in thread started by <function synch_data_loop at 0x02C20D20>
Traceback (most recent call last):
  File "F:\SublimeText\Data\Packages\BufferScroll\BufferScroll.py", line 909, in synch_data_loop
    if not Pref.synch_data_running:
AttributeError: type object 'Pref' has no attribute 'synch_data_running'
reloading settings Packages/User/BufferScroll.sublime-settings
Traceback (most recent call last):
  File "F:\SublimeText\sublime_plugin.py", line 280, in <lambda>
    lambda: check_view_event_listeners(view))
  File "F:\SublimeText\sublime_plugin.py", line 267, in check_view_event_listeners
    want = is_view_event_listener_applicable(cls, view)
  File "F:\SublimeText\sublime_plugin.py", line 232, in is_view_event_listener_applicable
    if not cls.is_applicable(view.settings()):
  File "F:\SublimeText\Data\Packages\LSP\plugin\completion.py", line 139, in is_applicable
    return is_supported_syntax(syntax)
TypeError: 'NoneType' object is not callable
indexing [job 29]: spawning 1 workers to process 2 / 2 files
indexing [job 29]: indexed 2 files
FuzzyFilePath cached 8314 files in F:/SublimeText/Data
Traceback (most recent call last):
  File "F:\SublimeText\sublime_plugin.py", line 280, in <lambda>
    lambda: check_view_event_listeners(view))
  File "F:\SublimeText\sublime_plugin.py", line 267, in check_view_event_listeners
    want = is_view_event_listener_applicable(cls, view)
  File "F:\SublimeText\sublime_plugin.py", line 232, in is_view_event_listener_applicable
    if not cls.is_applicable(view.settings()):
  File "F:\SublimeText\Data\Packages\LSP\plugin\completion.py", line 139, in is_applicable
    return is_supported_syntax(syntax)
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "F:\SublimeText\sublime_plugin.py", line 417, in run_async_view_listener_callback
    vel.__class__.__dict__[name](vel)
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\documents.py", line 244, in on_activated_async
    Events.publish("view.on_activated_async", self.view)
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\events.py", line 28, in publish
    listener(*args)
  File "F:\SublimeText\Data\Packages\LSP\plugin\configuration.py", line 16, in detect_supportable_view
    config = config_for_scope(view)
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "F:\SublimeText\sublime_plugin.py", line 280, in <lambda>
    lambda: check_view_event_listeners(view))
  File "F:\SublimeText\sublime_plugin.py", line 267, in check_view_event_listeners
    want = is_view_event_listener_applicable(cls, view)
  File "F:\SublimeText\sublime_plugin.py", line 232, in is_view_event_listener_applicable
    if not cls.is_applicable(view.settings()):
  File "F:\SublimeText\Data\Packages\LSP\plugin\completion.py", line 139, in is_applicable
    return is_supported_syntax(syntax)
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "F:\SublimeText\sublime_plugin.py", line 654, in on_text_command
    res = callback.on_text_command(v, name, args)
  File "F:\SublimeText\Data\Packages\LSP\plugin\completion.py", line 74, in on_text_command
    if settings.resolve_completion_for_snippets and current_completion:
AttributeError: 'NoneType' object has no attribute 'resolve_completion_for_snippets'
Traceback (most recent call last):
  File "F:\SublimeText\sublime_plugin.py", line 389, in run_callback
    expr()
  File "F:\SublimeText\sublime_plugin.py", line 496, in <lambda>
    run_callback('on_modified', callback, lambda: callback.on_modified(v))
  File "F:\SublimeText\Data\Packages\LSP\plugin\completion.py", line 80, in on_modified
    if settings.resolve_completion_for_snippets and view.file_name():
AttributeError: 'NoneType' object has no attribute 'resolve_completion_for_snippets'
Traceback (most recent call last):
  File "F:\SublimeText\sublime_plugin.py", line 425, in on_load
    attach_view(v)
  File "F:\SublimeText\sublime_plugin.py", line 276, in attach_view
    check_view_event_listeners(view)
  File "F:\SublimeText\sublime_plugin.py", line 267, in check_view_event_listeners
    want = is_view_event_listener_applicable(cls, view)
  File "F:\SublimeText\sublime_plugin.py", line 232, in is_view_event_listener_applicable
    if not cls.is_applicable(view.settings()):
  File "F:\SublimeText\Data\Packages\LSP\plugin\completion.py", line 139, in is_applicable
    return is_supported_syntax(syntax)
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "F:\SublimeText\sublime_plugin.py", line 280, in <lambda>
    lambda: check_view_event_listeners(view))
  File "F:\SublimeText\sublime_plugin.py", line 267, in check_view_event_listeners
    want = is_view_event_listener_applicable(cls, view)
  File "F:\SublimeText\sublime_plugin.py", line 232, in is_view_event_listener_applicable
    if not cls.is_applicable(view.settings()):
  File "F:\SublimeText\Data\Packages\LSP\plugin\completion.py", line 139, in is_applicable
    return is_supported_syntax(syntax)
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "F:\SublimeText\sublime_plugin.py", line 417, in run_async_view_listener_callback
    vel.__class__.__dict__[name](vel)
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\documents.py", line 244, in on_activated_async
    Events.publish("view.on_activated_async", self.view)
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\events.py", line 28, in publish
    listener(*args)
  File "F:\SublimeText\Data\Packages\LSP\plugin\configuration.py", line 16, in detect_supportable_view
    config = config_for_scope(view)
TypeError: 'NoneType' object is not callable
```
</p>
</details><br>

It throws a new error of these every time I change the selection on the view:
```
Traceback (most recent call last):
  File "F:\SublimeText\sublime_plugin.py", line 417, in run_async_view_listener_callback
    vel.__class__.__dict__[name](vel)
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\documents.py", line 244, in on_activated_async
    Events.publish("view.on_activated_async", self.view)
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\events.py", line 28, in publish
    listener(*args)
  File "F:\SublimeText\Data\Packages\LSP\plugin\configuration.py", line 16, in detect_supportable_view
    config = config_for_scope(view)
TypeError: 'NoneType' object is not callable
```

**Comment by tomv564** [comment]
A fix for #250 has been pushed.
As LSP was obviously in a broken state after that error, please restart Sublime Text instead of submitting more issues.
