### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'send_request'

### ISSUE THREAD

**Issue by evandrocoan** [tomv564/LSP#276]
```
Traceback (most recent call last):
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\clients.py", line 159, in check_window_unloaded
    unload_window_clients(closed_window_id)
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\clients.py", line 169, in unload_window_clients
    unload_client(state.client, window_id, config_name)
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\clients.py", line 210, in unload_client
    client.send_request(Request.shutdown(), lambda response: on_shutdown(client, window_id, config_name, response))
AttributeError: 'NoneType' object has no attribute 'send_request'
```

Language server log + LSP log:
```
2018-02-17 05:19:19,746 DEBUG pyls.rpc_manager:notify:78 Notify textDocument/publishDiagnostics {'uri': 'file:///F:/SublimeText/Data/Packages/AmxxChannel/settings.py', 'diagnostics': [{'source': 'pyflakes', 'range': {'start': {'line': 30, 'character': 0}, 'end': {'line': 30, 'character': 15}}, 'message': "'sublime' imported but unused", 'severity': 2}, {'source': 'pydocstyle', 'code': 'D100', 'message': 'D100: Missing docstring in public module', 'severity': 2, 'range': {'start': {'line': 0, 'character': 0}, 'end': {'line': 0, 'character': 23}}}, {'source': 'pydocstyle', 'code': 'D103', 'message': 'D103: Missing docstring in public function', 'severity': 2, 'range': {'start': {'line': 44, 'character': 0}, 'end': {'line': 44, 'character': 23}}}]}
2018-02-17 05:19:19,749 DEBUG pyls.json_rpc_server:write_message:82 Sending <jsonrpc.jsonrpc2.JSONRPC20Request object at 0x000001BDBBF490F0>
[LSP] 05:19:19:753.125906 <--  textDocument/publishDiagnostics
[LSP] 05:19:19:753.622055 Unhandled request textDocument/publishDiagnostics
[LSP] 05:23:10:703.984976 initialize on open 2 F:\SublimeText\Data\Packages\LSP\plugin\core\clients.py
[LSP] 05:23:10:735.018969  --> textDocument/didOpen
[LSP] 05:23:10:736.552000 unloading client pyls <LSP.plugin.core.rpc.Client object at 0x054ACAF0>
[LSP] 05:23:10:737.020016  --> shutdown
[LSP] 05:23:10:738.017082 window closed 6
[LSP] 05:23:10:738.522053 unloading client pyls <LSP.plugin.core.rpc.Client object at 0x054ACAF0>
[LSP] 05:23:10:739.022017  --> shutdown
2018-02-17 05:23:10,738 DEBUG pyls.rpc_manager:_handle_request:131 Sync request 2
2018-02-17 05:23:10,741 DEBUG pyls.json_rpc_server:write_message:82 Sending <jsonrpc.jsonrpc2.JSONRPC20Response object at 0x00000160435A8400>
[LSP] 05:23:10:745.523930  --> exit
[LSP] 05:23:10:746.524096 all clients unloaded
[LSP] 05:23:10:747.025967 clients for window 6 unloaded
[LSP] 05:23:11:021.785021 LSP stderr process ended.
[LSP] 05:23:11:023.787022 LSP stdout process ended.
[LSP] 05:23:11:706.952095 initialize on open 2 F:\SublimeText\Data\Packages\LSP\plugin\core\clients.py
2018-02-17 05:23:10,741 DEBUG pyls.python_ls:_hook:115 PythonLanguageServer, self.config: Config. _root_path: f:\SublimeText\Data, _root_uri: file:///F:/SublimeText/Data, _init_opts: {}, _settings: {'plugins': {'rope': {'create_folder': False}, 'pydocstyle': {'enabled': True, 'ignore': ['D202', 'D208']}, 'pycodestyle': {'enabled': False}}}, _plugin_settings: {'plugins': {'pydocstyle': {'enabled': False}, 'rope_completion': {'enabled': False}}}, _disabled_plugins: [<module 'pyls.plugins.pycodestyle_lint' from 'd:\\user\\dropbox\\softwareversioning\\python-language-server\\pyls\\plugins\\pycodestyle_lint.py'>], _config_sources(flake8): Flake8Config. root_path: f:\SublimeText\Data, is_windows: True, xdg_home: C:\Users\Professional/.config, _modified_times: {}, _config_sources(pycodestyle): PyCodeStyleConfig. root_path: f:\SublimeText\Data, is_windows: True, xdg_home: C:\Users\Professional/.config, _modified_times: {(): ()}, _configs_cache(()): []
2018-02-17 05:23:11,758 DEBUG pyls.config.config:processmessage:137   pyls_document_did_open [hook]
      config: Config. _root_path: f:\SublimeText\Data, _root_uri: file:///F:/SublimeText/Data, _init_opts: {}, _settings: {'plugins': {'rope': {'create_folder': False}, 'pydocstyle': {'enabled': True, 'ignore': ['D202', 'D208']}, 'pycodestyle': {'enabled': False}}}, _plugin_settings: {'plugins': {'pydocstyle': {'enabled': False}, 'rope_completion': {'enabled': False}}}, _disabled_plugins: [<module 'pyls.plugins.pycodestyle_lint' from 'd:\\user\\dropbox\\softwareversioning\\python-language-server\\pyls\\plugins\\pycodestyle_lint.py'>], _config_sources(flake8): Flake8Config. root_path: f:\SublimeText\Data, is_windows: True, xdg_home: C:\Users\Professional/.config, _modified_times: {}, _config_sources(pycodestyle): PyCodeStyleConfig. root_path: f:\SublimeText\Data, is_windows: True, xdg_home: C:\Users\Professional/.config, _modified_times: {(): ()}, _configs_cache(()): []
      workspace: Workspace. _root_path: f:\SublimeText\Data, _root_uri: file:///F:/SublimeText/Data, _root_uri_scheme: file, _rpc_manager: JSONRPCManager. _message_manager: <pyls.json_rpc_server.JSONRPCServer object at 0x000001BDBAC40F60>, _message_handler: <bound method PythonLanguageServer.handle_request of <pyls.python_ls.PythonLanguageServer object at 0x000001BDB9F957F0>>, _shutdown: False, _sent_requests: {}, _received_requests: {}, _executor_service: <concurrent.futures.thread.ThreadPoolExecutor object at 0x000001BDBAC4CE80>, __rope: Project. _address: f:\SublimeText\Data, _ropefolder_name: None, ignored: _ResourceMatcher. patterns: [], file_list: None, prefs: Prefs. {'extension_modules': ['numpy', 'os', 'array', 'audioop', 'binascii', 'cmath', 'collections', 'datetime', 'errno', 'gc', 'imp', 'itertools', 'marshal', 'math', 'mmap', 'msvcrt', 'nt', 'operator', 'parser', 'signal', 'sys', 'time', 'xxsubtype', 'zipimport', 'zlib']}, callbacks: {'ignored_resources': <bound method _ResourceMatcher.set_patterns of <rope.base.resources._ResourceMatcher object at 0x000001BDBBDBF5F8>>}, _docs(file:///F:/SublimeText/Data/Packages/AmxxChannel/settings.py): Document. uri: file:///F:/SublimeText/Data/Packages/AmxxChannel/settings.py, version: 33, path: f:\SublimeText\Data\Packages\AmxxChannel\settings.py, filename: settings.py, _local: True, _extra_sys_path: [], _rope_project: Project. _address: f:\SublimeText\Data, _ropefolder_name: None, ignored: _ResourceMatcher. patterns: [], file_list: None, prefs: Prefs. {'extension_modules': ['numpy', 'os', 'array', 'audioop', 'binascii', 'cmath', 'collections', 'datetime', 'errno', 'gc', 'imp', 'itertools', 'marshal', 'math', 'mmap', 'msvcrt', 'nt', 'operator', 'parser', 'signal', 'sys', 'time', 'xxsubtype', 'zipimport', 'zlib']}, callbacks: {'ignored_resources': <bound method _ResourceMatcher.set_patterns of <rope.base.resources._ResourceMatcher object at 0x000001BDBBDBF5F8>>}, _docs(file:///F:/SublimeText/Data/Packages/ChannelManager/all/channel_manager/channel_utilities.py): Document. uri: file:///F:/SublimeText/Data/Packages/ChannelManager/all/channel_manager/channel_utilities.py, version: 7, path: f:\SublimeText\Data\Packages\ChannelManager\all\channel_manager\channel_utilities.py, filename: channel_utilities.py, _local: True, _extra_sys_path: [], _rope_project: Project. _address: f:\SublimeText\Data, _ropefolder_name: None, ignored: _ResourceMatcher. patterns: [], file_list: None, prefs: Prefs. {'extension_modules': ['numpy', 'os', 'array', 'audioop', 'binascii', 'cmath', 'collections', 'datetime', 'errno', 'gc', 'imp', 'itertools', 'marshal', 'math', 'mmap', 'msvcrt', 'nt', 'operator', 'parser', 'signal', 'sys', 'time', 'xxsubtype', 'zipimport', 'zlib']}, callbacks: {'ignored_resources': <bound method _ResourceMatcher.set_patterns of <rope.base.resources._ResourceMatcher object at 0x000001BDBBDBF5F8>>}, _docs(file:///F:/SublimeText/Data/Packages/ChannelManager/all/channel_manager/channel_manager.py): Document. uri: file:///F:/SublimeText/Data/Packages/ChannelManager/all/channel_manager/channel_manager.py, version: 28, path: f:\SublimeText\Data\Packages\ChannelManager\all\channel_manager\channel_manager.py, filename: channel_manager.py, _local: True, _extra_sys_path: [], _rope_project: Project. _address: f:\SublimeText\Data, _ropefolder_name: None, ignored: _ResourceMatcher. patterns: [], file_list: None, prefs: Prefs. {'extension_modules': ['numpy', 'os', 'array', 'audioop', 'binascii', 'cmath', 'collections', 'datetime', 'errno', 'gc', 'imp', 'itertools', 'marshal', 'math', 'mmap', 'msvcrt', 'nt', 'operator', 'parser', 'signal', 'sys', 'time', 'xxsubtype', 'zipimport', 'zlib']}, callbacks: {'ignored_resources': <bound method _ResourceMatcher.set_patterns of <rope.base.resources._ResourceMatcher object at 0x000001BDBBDBF5F8>>}, _docs(file:///F:/SublimeText/Data/Packages/Amxmodx/Amxmodx.py): Document. uri: file:///F:/SublimeText/Data/Packages/Amxmodx/Amxmodx.py, version: 0, path: f:\SublimeText\Data\Packages\Amxmodx\Amxmodx.py, filename: Amxmodx.py, _local: True, _extra_sys_path: [], _rope_project: Project. _address: f:\SublimeText\Data, _ropefolder_name: None, ignored: _ResourceMatcher. patterns: [], file_list: None, prefs: Prefs. {'extension_modules': ['numpy', 'os', 'array', 'audioop', 'binascii', 'cmath', 'collections', 'datetime', 'errno', 'gc', 'imp', 'itertools', 'marshal', 'math', 'mmap', 'msvcrt', 'nt', 'operator', 'parser', 'signal', 'sys', 'time', 'xxsubtype', 'zipimport', 'zlib']}, callbacks: {'ignored_resources': <bound method _ResourceMatcher.set_patterns of <rope.base.resources._ResourceMatcher object at 0x000001BDBBDBF5F8>>}, _docs(file:///F:/SublimeText/Data/Packages/ChannelManager/all/channel_manager/channel_installer.py): Document. uri: file:///F:/SublimeText/Data/Packages/ChannelManager/all/channel_manager/channel_installer.py, version: 0, path: f:\SublimeText\Data\Packages\ChannelManager\all\channel_manager\channel_installer.py, filename: channel_installer.py, _local: True, _extra_sys_path: [], _rope_project: Project. _address: f:\SublimeText\Data, _ropefolder_name: None, ignored: _ResourceMatcher. patterns: [], file_list: None, prefs: Prefs. {'extension_modules': ['numpy', 'os', 'array', 'audioop', 'binascii', 'cmath', 'collections', 'datetime', 'errno', 'gc', 'imp', 'itertools', 'marshal', 'math', 'mmap', 'msvcrt', 'nt', 'operator', 'parser', 'signal', 'sys', 'time', 'xxsubtype', 'zipimport', 'zlib']}, callbacks: {'ignored_resources': <bound method _ResourceMatcher.set_patterns of <rope.base.resources._ResourceMatcher object at 0x000001BDBBDBF5F8>>}, _docs(file:///F:/SublimeText/Data/Packages/LSP/plugin/core/clients.py): Document. uri: file:///F:/SublimeText/Data/Packages/LSP/plugin/core/clients.py, version: 0, path: f:\SublimeText\Data\Packages\LSP\plugin\core\clients.py, filename: clients.py, _local: True, _extra_sys_path: [], _rope_project: Project. _address: f:\SublimeText\Data, _ropefolder_name: None, ignored: _ResourceMatcher. patterns: [], file_list: None, prefs: Prefs. {'extension_modules': ['numpy', 'os', 'array', 'audioop', 'binascii', 'cmath', 'collections', 'datetime', 'errno', 'gc', 'imp', 'itertools', 'marshal', 'math', 'mmap', 'msvcrt', 'nt', 'operator', 'parser', 'signal', 'sys', 'time', 'xxsubtype', 'zipimport', 'zlib']}, callbacks: {'ignored_resources': <bound method _ResourceMatcher.set_patterns of <rope.base.resources._ResourceMatcher object at 0x000001BDBBDBF5F8>>}
      document: Document. uri: file:///F:/SublimeText/Data/Packages/LSP/plugin/core/clients.py, version: 0, path: f:\SublimeText\Data\Packages\LSP\plugin\core\clients.py, filename: clients.py, _local: True, _extra_sys_path: [], _rope_project: Project. _address: f:\SublimeText\Data, _ropefolder_name: None, ignored: _ResourceMatcher. patterns: [], file_list: None, prefs: Prefs. {'extension_modules': ['numpy', 'os', 'array', 'audioop', 'binascii', 'cmath', 'collections', 'datetime', 'errno', 'gc', 'imp', 'itertools', 'marshal', 'math', 'mmap', 'msvcrt', 'nt', 'operator', 'parser', 'signal', 'sys', 'time', 'xxsubtype', 'zipimport', 'zlib']}, callbacks: {'ignored_resources': <bound method _ResourceMatcher.set_patterns of <rope.base.resources._ResourceMatcher object at 0x000001BDBBDBF5F8>>}
```

**Comment by tomv564** [comment]
I see this two times in your logs:
```
unloading client pyls <LSP.plugin.core.rpc.Client object at 0x054ACAF0>
```
I wonder why the shutdown logic is being ran twice?
As I have no idea what
