### ISSUE TITLE
TypeError: int() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by evandrocoan** [tomv564/LSP#277]
So, the response can be `None`, or it is a problem on the language server?
```
[LSP] 06:05:51:512.800932 Error handling server payload
Traceback (most recent call last):
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\rpc.py", line 322, in receive_payload
    self.response_handler(payload)
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\rpc.py", line 335, in response_handler
    handler_id = int(response.get("id"))  # dotty sends strings back :(
TypeError: int() argument must be a string or a number, not 'NoneType'
```

Server log + LSP log
```
[LSP] 06:05:51:457.748890  --> initialized
[LSP] 06:05:51:458.750010  --> workspace/didChangeConfiguration
[LSP] 06:05:51:459.752083 pyls client registered for window 2
2018-02-17 06:05:51,459 DEBUG pyls.rpc_manager:_handle_request:122 No handler found for initialized
2018-02-17 06:05:51,462 DEBUG pyls.json_rpc_server:write_message:82 Sending <jsonrpc.jsonrpc2.JSONRPC20Response object at 0x000002BC5AF0D828>
2018-02-17 06:05:51,464 INFO pyls.config.config:update:116 Updated settings to {'plugins': {'pydocstyle': {'enabled': True, 'ignore': ['D202', 'D208']}, 'pycodestyle': {'enabled': False}, 'rope': {'create_folder': False}}}
2018-02-17 06:05:51,467 INFO pyls.config.config:update:123 Disabled plugins: [<module 'pyls.plugins.pycodestyle_lint' from 'd:\\user\\dropbox\\softwareversioning\\python-language-server\\pyls\\plugins\\pycodestyle_lint.py'>]
[LSP] 06:05:51:508.797884  --> textDocument/didOpen
[LSP] 06:05:51:512.800932 Error handling server payload
Traceback (most recent call last):
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\rpc.py", line 322, in receive_payload
    self.response_handler(payload)
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\rpc.py", line 335, in response_handler
    handler_id = int(response.get("id"))  # dotty sends strings back :(
TypeError: int() argument must be a string or a number, not 'NoneType'
2018-02-17 06:05:51,515 DEBUG pyls.python_ls:_hook:115 PythonLanguageServer, self.config: Config. _root_path: f:\SublimeText\Data, _root_uri: file:///F:/SublimeText/Data, _init_opts: {}, _settings: {'plugins': {'pydocstyle': {'enabled': True, 'ignore': ['D202', 'D208']}, 'pycodestyle': {'enabled': False}, 'rope': {'create_folder': False}}}, _plugin_settings: {'plugins': {'pydocstyle': {'enabled': False}, 'rope_completion': {'enabled': False}}}, _disabled_plugins: [<module 'pyls.plugins.pycodestyle_lint' from 'd:\\user\\dropbox\\softwareversioning\\python-language-server\\pyls\\plugins\\pycodestyle_lint.py'>], _config_sources(flake8): Flake8Config. root_path: f:\SublimeText\Data, is_windows: True, xdg_home: C:\Users\Professional/.config, _modified_times: {}, _config_sources(pycodestyle): PyCodeStyleConfig. root_path: f:\SublimeText\Data, is_windows: True, xdg_home: C:\Users\Professional/.config, _modified_times: {}
2018-02-17 06:05:51,526 DEBUG pyls.config.config:processmessage:137   pyls_document_did_open [hook]
      config: Config. _root_path: f:\SublimeText\Data, _root_uri: file:///F:/SublimeText/Data, _init_opts: {}, _settings: {'plugins': {'pydocstyle': {'enabled': True, 'ignore': ['D202', 'D208']}, 'pycodestyle': {'enabled': False}, 'rope': {'create_folder': False}}}, _plugin_settings: {'plugins': {'pydocstyle': {'enabled': False}, 'rope_completion': {'enabled': False}}}, _disabled_plugins: [<module 'pyls.plugins.pycodestyle_lint' from 'd:\\user\\dropbox\\softwareversioning\\python-language-server\\pyls\\plugins\\pycodestyle_lint.py'>], _config_sources(flake8): Flake8Config. root_path: f:\SublimeText\Data, is_windows: True, xdg_home: C:\Users\Professional/.config, _modified_times: {}, _config_sources(pycodestyle): PyCodeStyleConfig. root_path: f:\SublimeText\Data, is_windows: True, xdg_home: C:\Users\Professional/.config, _modified_times: {}
      workspace: Workspace. _root_path: f:\SublimeText\Data, _root_uri: file:///F:/SublimeText/Data, _root_uri_scheme: file, _rpc_manager: JSONRPCManager. _message_manager: <pyls.json_rpc_server.JSONRPCServer object at 0x000002BC589F9B00>, _message_handler: <bound method PythonLanguageServer.handle_request of <pyls.python_ls.PythonLanguageServer object at 0x000002BC590E57F0>>, _shutdown: False, _sent_requests: {}, _received_requests: {}, _executor_service: <concurrent.futures.thread.ThreadPoolExecutor object at 0x000002BC59DBDF60>, __rope: Project. _address: f:\SublimeText\Data, _ropefolder_name: None, ignored: _ResourceMatcher. patterns: [], file_list: None, prefs: Prefs. {'extension_modules': ['numpy', 'os', 'array', 'audioop', 'binascii', 'cmath', 'collections', 'datetime', 'errno', 'gc', 'imp', 'itertools', 'marshal', 'math', 'mmap', 'msvcrt', 'nt', 'operator', 'parser', 'signal', 'sys', 'time', 'xxsubtype', 'zipimport', 'zlib']}, callbacks: {'ignored_resources': <bound method _ResourceMatcher.set_patterns of <rope.base.resources._ResourceMatcher object at 0x000002BC5AF5DF28>>}, _docs(file:///F:/SublimeText/Data/Packages/LSP/plugin/core/clients.py): Document. uri: file:///F:/SublimeText/Data/Packages/LSP/plugin/core/clients.py, version: 0, path: f:\SublimeText\Data\Packages\LSP\plugin\core\clients.py, filename: clients.py, _local: True, _extra_sys_path: [], _rope_project: Project. _address: f:\SublimeText\Data, _ropefolder_name: None, ignored: _ResourceMatcher. patterns: [], file_list: None, prefs: Prefs. {'extension_modules': ['numpy', 'os', 'array', 'audioop', 'binascii', 'cmath', 'collections', 'datetime', 'errno', 'gc', 'imp', 'itertools', 'marshal', 'math', 'mmap', 'msvcrt', 'nt', 'operator', 'parser', 'signal', 'sys', 'time', 'xxsubtype', 'zipimport', 'zlib']}, callbacks: {'ignored_resources': <bound method _ResourceMatcher.set_patterns of <rope.base.resources._ResourceMatcher object at 0x000002BC5AF5DF28>>}
      document: Document. uri: file:///F:/SublimeText/Data/Packages/LSP/plugin/core/clients.py, version: 0, path: f:\SublimeText\Data\Packages\LSP\plugin\core\clients.py, filename: clients.py, _local: True, _extra_sys_path: [], _rope_project: Project. _address: f:\SublimeText\Data, _ropefolder_name: None, ignored: _ResourceMatcher. patterns: [], file_list: None, prefs: Prefs. {'extension_modules': ['numpy', 'os', 'array', 'audioop', 'binascii', 'cmath', 'collections', 'datetime', 'errno', 'gc', 'imp', 'itertools', 'marshal', 'math', 'mmap', 'msvcrt', 'nt', 'operator', 'parser', 'signal', 'sys', 'time', 'xxsubtype', 'zipimport', 'zlib']}, callbacks: {'ignored_resources': <bound method _ResourceMatcher.set_patterns of <rope.base.resources._ResourceMatcher object at 0x000002BC5AF5DF28>>}

2018-02-17 06:05:51,529 DEBUG pyls.config.config:processmessage:137   finish pyls_document_did_open --> [] [hook]
```

Related:

1. https://github.com/palantir/python-language-server/pull/261 Add support for asynchronously handling requests

**Comment by ferozco** [comment]
The spec says that the value of id should not be null, but can be strings, numbers or null. http://www.jsonrpc.org/specification#id1

What client are you using? It appears as if it makes the assumption that if id exists then it must be a real value and not null.

I think you're running into this issue with the changes introduced in my async PR  because of https://github.com/palantir/python-language-server/pull/261/files#diff-ca8360ff7619f1366f738c05b42479f4R68 . Here we send notifications (in this case a diagnostics notification in response to didOpen) with an null id.

Thanks, for catching that. Happy to change it so that we more closely adhere to JSON RPC best practices. 

I would also recommend opening an issue on the client you use (if possible) since technically their implementation does not full support the spec

**Comment by tomv564** [comment]
Thanks @ferozco for consulting the spec, it states that
> A Notification is a Request object without an "id" member. 

So, null values are not expected for notifications and pyls would be the only server to have this behaviour.

As for requests, the spec says this:
> The use of Null as a value for the id member in a Request object is discouraged

So I would like to avoid merging #278 - the higher our implementation follows the spec the easier to spot errors in language servers.

**Comment by ferozco** [comment]
ahh my bad. Totally agree, lets close my PR. I've already made the required change to PyLS as well

**Comment by evandrocoan** [comment]
Even after they not sending None anymore, it still doing the error as:
```python
>>> print({}.get("id"))
None
```

**Comment by evandrocoan** [comment]
Just noticed this before:
```python
File: Data/Packages/LSP/plugin/core/rpc.py
326:             elif "id" in payload:
327:                 self.response_handler(payload)
```
