### ISSUE TITLE
LSP very often causes deadlocks in cooperation with pyls

### ISSUE THREAD

**Issue by deathaxe** [tomv564/LSP#287]
* OS and language server : Windows 10 Pro 1709 / pyls 0.14.0
* How you installed LSP (Package Control or from git?) : current master (d6da33ba061820c15b99d4f912d09d5f323dceef)

As the title says, ST 3157 gets locked up completely quite often when editing python files. Killing the pyls.exe via TaskManager resolves the issue. LSP detects the broken pipe error then and asks to restart pyls. Even though it is possible to recover from that situation it is very annoying.

Tried to do some logging/debugging, but can't really find the reason for freezing. It just looks like some mutex/lock not being released correctly causing a deadlock at some point.

The issue happens with both `stdio` and `tcp` interface, while `stdio` seems to suffer from that more often.

LSP config

```
{
	"auto_show_diagnostics_panel": false,
	"clients":
	{
		"pyls":
		{
			"enabled": true,
			 "command": ["pyls", "--log-file", "C:\\data\\pyls.log", "-vv"]
			// "command": ["pyls", "--tcp", "--log-file", "C:\\data\\pyls.log", "-vv"],
			// "tcp_port": 2087,
		}
	},
	"show_diagnostics_in_view_status": false,
	"only_show_lsp_completions": false,
	"log_debug": true,
	"log_server": true,
	// "log_payloads": true,
}
```

Console log 
```
LSP: initialize on open 2 C:\Apps\Sublime\Data\Packages\GitGutter\modules\temp.py
LSP: initialize on open 2 C:\Apps\Sublime\Data\Packages\GitGutter\modules\handler.py
LSP:  --> textDocument/hover
LSP:  --> textDocument/didChange
LSP: <--  textDocument/publishDiagnostics
LSP:  --> textDocument/didChange
LSP:  --> textDocument/completion
LSP: <--  textDocument/publishDiagnostics
LSP:  --> textDocument/didChange
LSP: <--  textDocument/publishDiagnostics
LSP:  --> textDocument/didChange
LSP: <--  textDocument/publishDiagnostics
LSP:  --> textDocument/didChange
LSP:  --> textDocument/signatureHelp
LSP: <--  textDocument/publishDiagnostics
LSP:  --> textDocument/didChange
LSP:  --> textDocument/signatureHelp
LSP:  --> textDocument/didChange
LSP: <--  textDocument/publishDiagnostics
LSP:  --> textDocument/hover
Failure writing to stdout
Traceback (most recent call last):
  File "C:\Apps\Sublime\Data\Packages\LSP\plugin\core\rpc.py", line 229, in send
    self.process.stdin.flush()
OSError: [Errno 22] Invalid argument

Failure writing to stdout
LSP: LSP stdout process ended.
Traceback (most recent call last):
  File "C:\Apps\Sublime\Data\Packages\LSP\plugin\core\rpc.py", line 228, in send
    self.process.stdin.write(bytes(message, 'UTF-8'))
BrokenPipeError: [Errno 32] Broken pipe

LSP:  --> textDocument/signatureHelp
LSP: initialize on open 2 C:\Apps\Sublime\Data\Packages\GitGutter\modules\handler.py
LSP: initialize on open 2 C:\Apps\Python33\Lib\tempfile.py
LSP:  --> textDocument/didChange
LSP: initialize on open 2 C:\Apps\Python33\Lib\tempfile.py
LSP: initialize on open 2 C:\Apps\Sublime\Data\Packages\GitGutter\modules\handler.py
```

At some point ST froze and I killed pyls.exe. As the console was not open at that point of time, I can only guess the Errno32 being a result of killing pyls.

**Comment by tomv564** [comment]
Thanks for so many details, I had hoped that `pyls`'s switch to async rpc would help. There is some discussion at https://github.com/palantir/python-language-server/issues/257 suggesting the situation has become worse.

I see you were logging `pyls`'s output as well, any chance we can correlate what was happening on the server side?

**Comment by deathaxe** [comment]
Unfortunately I accidentally deleted the file catching this special situation. As soon as I find myself in such a situation again, I'll carefully copy and paste the log of both sides.

**Comment by rwols** [comment]
I'm also experiencing quite frequent deadlocks on ubuntu 17.10 with release 0.50 at work.

**Comment by rwols** [comment]
And also with the master branch. Not sure what's going on because I don't experience this on my mac at home.

**Comment by tomv564** [comment]
Please keep sharing data points, eventually we'll narrow it down. It also can't hurt to review what sync handlers we have. Finally, there's another issue here where we had a bit more discussion about sublime's threading with plugins.

**Comment by rwols** [comment]
OK, I managed to reproduce this (I think?) on my macbook when turning off all logging. Here's a stack trace from plugin_host:

<details><summary>Stacktrace</summary><p>

```
Process:         plugin_host [12264]
Path:            /Applications/Sublime Text.app/Contents/MacOS/plugin_host
Architecture:    x86_64
Parent:          Sublime Text [12263]
Responsible:     Sublime Text [12263]
UID:             501
Task size:       70.40 MB
Note:            1 idle work queue threads omitted

  Thread 0x2bc1d            DispatchQueue 1           10 samples (1-10)         priority 31 (base 31)
  <thread QoS default (requested user interactive), IO tier 0>
  10  start + 52 (plugin_host + 5940) [0x1004a2734] 1-10
    10  main + 579 (plugin_host + 158673) [0x1004c7bd1] 1-10
      10  handle_protocol_message(string_buffer const&) + 885 (plugin_host + 150666) [0x1004c5c8a] 1-10
        10  void decode_message<int, object_id, int>(int (*)(object_id, int), binary_input_stream&) + 97 (plugin_host + 157879) [0x1004c78b7] 1-10
          10  plugin_call_int(object_id, int) + 86 (plugin_host + 66549) [0x1004b13f5] 1-10
            10  PyEval_CallObjectWithKeywords + 93 (plugin_host + 1079287) [0x1005a87f7] 1-10
              10  PyObject_Call + 103 (plugin_host + 462070) [0x100511cf6] 1-10
                10  function_call + 365 (plugin_host + 590889) [0x100531429] 1-10
                  10  PyEval_EvalCodeEx + 1622 (plugin_host + 1045776) [0x1005a0510] 1-10
                    10  PyEval_EvalFrameEx + 20335 (plugin_host + 1066550) [0x1005a5636] 1-10
                      10  fast_function + 321 (plugin_host + 1082318) [0x1005a93ce] 1-10
                        10  PyEval_EvalCodeEx + 1622 (plugin_host + 1045776) [0x1005a0510] 1-10
                          10  PyEval_EvalFrameEx + 20335 (plugin_host + 1066550) [0x1005a5636] 1-10
                            10  fast_function + 321 (plugin_host + 1082318) [0x1005a93ce] 1-10
                              10  PyEval_EvalCodeEx + 1622 (plugin_host + 1045776) [0x1005a0510] 1-10
                                10  PyEval_EvalFrameEx + 20546 (plugin_host + 1066761) [0x1005a5709] 1-10
                                  10  _object* call_function_release_gil<unsigned int, unsigned int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int, int>(unsigned int (*)(unsigned int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int, int), _object*) + 183 (plugin_host + 44781) [0x1004abeed] 1-10
                                    10  api_window_open_file(unsigned int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int, int) + 34 (plugin_host + 44882) [0x1004abf52] 1-10
                                      10  unsigned int send_helper<unsigned int>::send_message<165u, unsigned int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned int, int>(unsigned int const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int const&, int const&) + 277 (plugin_host + 130915) [0x1004c0f63] 1-10
                                        10  void wait_for_reply<unsigned int>(reply_entry*, unsigned int*) + 141 (plugin_host + 182815) [0x1004cda1f] 1-10
                                          10  handle_protocol_message(string_buffer const&) + 424 (plugin_host + 150205) [0x1004c5abd] 1-10
                                            10  void decode_message<int, unsigned int>(int (*)(unsigned int), binary_input_stream&) + 75 (plugin_host + 151498) [0x1004c5fca] 1-10
                                              10  plugin_on_close(unsigned int) + 34 (plugin_host + 58331) [0x1004af3db] 1-10
                                                10  void py_call<unsigned int>(char const*, char const*, unsigned int const&) + 127 (plugin_host + 57008) [0x1004aeeb0] 1-10
                                                  10  PyEval_CallObjectWithKeywords + 93 (plugin_host + 1079287) [0x1005a87f7] 1-10
                                                    10  PyObject_Call + 103 (plugin_host + 462070) [0x100511cf6] 1-10
                                                      10  function_call + 365 (plugin_host + 590889) [0x100531429] 1-10
                                                        10  PyEval_EvalCodeEx + 1622 (plugin_host + 1045776) [0x1005a0510] 1-10
                                                          10  PyEval_EvalFrameEx + 20335 (plugin_host + 1066550) [0x1005a5636] 1-10
                                                            10  fast_function + 203 (plugin_host + 1082200) [0x1005a9358] 1-10
                                                              10  PyEval_EvalFrameEx + 20335 (plugin_host + 1066550) [0x1005a5636] 1-10
                                                                10  fast_function + 321 (plugin_host + 1082318) [0x1005a93ce] 1-10
                                                                  10  PyEval_EvalCodeEx + 1622 (plugin_host + 1045776) [0x1005a0510] 1-10
                                                                    10  PyEval_EvalFrameEx + 20335 (plugin_host + 1066550) [0x1005a5636] 1-10
                                                                      10  fast_function + 203 (plugin_host + 1082200) [0x1005a9358] 1-10
                                                                        10  PyEval_EvalFrameEx + 20335 (plugin_host + 1066550) [0x1005a5636] 1-10
                                                                          10  fast_function + 321 (plugin_host + 1082318) [0x1005a93ce] 1-10
                                                                            10  PyEval_EvalCodeEx + 1622 (plugin_host + 1045776) [0x1005a0510] 1-10
                                                                              10  PyEval_EvalFrameEx + 22167 (plugin_host + 1068382) [0x1005a5d5e] 1-10
                                                                                10  PyObject_Call + 103 (plugin_host + 462070) [0x100511cf6] 1-10
                                                                                  10  function_call + 365 (plugin_host + 590889) [0x100531429] 1-10
                                                                                    10  PyEval_EvalCodeEx + 1622 (plugin_host + 1045776) [0x1005a0510] 1-10
                                                                                      10  PyEval_EvalFrameEx + 20335 (plugin_host + 1066550) [0x1005a5636] 1-10
                                                                                        10  fast_function + 203 (plugin_host + 1082200) [0x1005a9358] 1-10
                                                                                          10  PyEval_EvalFrameEx + 20335 (plugin_host + 1066550) [0x1005a5636] 1-10
                                                                                            10  fast_function + 203 (plugin_host + 1082200) [0x1005a9358] 1-10
                                                                                              10  PyEval_EvalFrameEx + 20335 (plugin_host + 1066550) [0x1005a5636] 1-10
                                                                                                10  fast_function + 203 (plugin_host + 1082200) [0x1005a9358] 1-10
                                                                                                  10  PyEval_EvalFrameEx + 20546 (plugin_host + 1066761) [0x1005a5709] 1-10
                                                                                                    10  bufferedwriter_write + 189 (plugin_host + 1938860) [0x10067a5ac] 1-10
                                                                                                      10  _enter_buffered_busy + 90 (plugin_host + 1940022) [0x10067aa36] 1-10
                                                                                                        10  PyThread_acquire_lock_timed + 272 (plugin_host + 1251392) [0x1005d2840] 1-10
                                                                                                          10  __psynch_cvwait + 10 (libsystem_kernel.dylib + 113902) [0x7fff778accee] 1-10
                                                                                                           *10  psynch_cvcontinue + 0 (pthread + 38976) [0xffffff7f83abe840] 1-10
```

</p></details>

After this, I did a git-bisect between `master` and `0.4.0`:

<details><summary>git-bisect details</summary><p>

```
~/L/A/S/P/LSP (master=) git fetch upstream --tags
From https://github.com/tomv564/LSP
 * [new tag]         0.5.0      -> 0.5.0
~/L/A/S/P/LSP (master=) git bisect start
~/L/A/S/P/LSP (master|BISECTING=) git bisect bad
~/L/A/S/P/LSP (master|BISECTING=) git bisect good 0.4.0
Bisecting: 45 revisions left to test after this (roughly 6 steps)
[be315dc3ac02c064d74dbccdca6f931044f32fe5] Fix variable name
~/L/A/S/P/LSP ((be315dc3…)|BISECTING) git bisect good
Bisecting: 22 revisions left to test after this (roughly 5 steps)
[67158b3f2b7c9b3009fdb6192a28332679a6593a] Squashed commit of the following:
~/L/A/S/P/LSP ((67158b3f…)|BISECTING) git bisect bad
Bisecting: 11 revisions left to test after this (roughly 4 steps)
[fea99e1ae4ea0df654cfcf5f53ae02a03a2bc955] cancel current completion if the previous input is a space
~/L/A/S/P/LSP ((fea99e1a…)|BISECTING) git bisect good
Bisecting: 5 revisions left to test after this (roughly 3 steps)
[6dcd17dd314ed2d07766617d885a8fc8b2a90d9d] Rename R settings key to prevent it overwriting Rust settings (#265)
~/L/A/S/P/LSP ((6dcd17dd…)|BISECTING) git bisect good
Bisecting: 2 revisions left to test after this (roughly 2 steps)
[b6a3b9dca2cf04fd14fe6602d6cb1fb22ae51679] Expose hover as command
~/L/A/S/P/LSP ((b6a3b9dc…)|BISECTING) git bisect bad
Bisecting: 0 revisions left to test after this (roughly 1 step)
[f665329cf976effac34ab61c757646d109b2ee03] Add issue template
~/L/A/S/P/LSP ((f665329c…)|BISECTING) git bisect bad
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[7ef826805d51eb76fbabd07506d5ec53bc329a3c] TCP support (#248)
~/L/A/S/P/LSP ((7ef82680…)|BISECTING) git bisect bad
7ef826805d51eb76fbabd07506d5ec53bc329a3c is the first bad commit
commit 7ef826805d51eb76fbabd07506d5ec53bc329a3c
Author: Tom van Ommeren <tom.vanommeren@gmail.com>
Date:   Fri Feb 2 08:05:30 2018 +0100

    TCP support (#248)

    * Add socket-based client activated when tcp_port is specified

    Tested against a manually started pyls --tcp

    * Extract Transport and TCP Transport

    * Update tcp parser for PHP language server

    * Also start server if tcp specified, wait for socket to open

    * Add stdio handler and narrow down error handling

    * Use same client for stdio and tcp

    * Re-enable log_stderr, reading stdout for TCP servers

    * Move startup and shutdown state into clients.py

    Properly recognize startup and shutdown state

    * Wait with restart until clients have received exit notification

    * didopen_after_initialize needs to be by window

    So we don't send didOpens from two starting windows to same server

    * Clean debug logging
```

</p></details>


According to my digging, 7ef826805d51eb76fbabd07506d5ec53bc329a3c is the first bad commit (it's always the big commits eh? :P). Can this be of any use?

**Comment by rwols** [comment]
It looks like you deleted the feature branch in https://github.com/tomv564/LSP/pull/248, do you still have it locally so that I can do a git bisect in that branch?

**Comment by rwols** [comment]
I seem to have a local copy of the feature-tcp-client branch, but it only goes up to adf08371006bbc565e72662265edc69a59716aa6. This commit seems to work OK! I also don't think f9117fa64e1889133ec7ee4fe7fd32ec7d2ab8bc would cause any problems, so the problem is somewhere between 430578a and b81ffb1.

**Comment by tomv564** [comment]
Sorry this took me so long to get back to, amazing detective work! How did you tell bisect that a given commit was bad?
I just pushed the branch with the missing commits added, hope it helps!

**Comment by tomv564** [comment]
This must be related to document-related events being fired at startup - I can confirm I had similar lockups with my typescript server last week (couldn't restart until all other documents were closed) so it's likely a fundamental issue with LSP.
Will have a closer look at that commit !

**Comment by deathaxe** [comment]
In case it helps somehow: LSP (with python) locked up ST recently most likely when adding/editing/removing function call parameters. Maybe the reason is related to the parameter hint popup?

**Comment by tomv564** [comment]
I looked closer at the suspicious commit, the intended change was to introduce a proper "starting" state for clients that are waiting for their language server to start up.
The condition `if config_state.client:` in `_client_for_view_and_window` should prevent LSP features accessing the server too early. This doesn't feel like it should cause deadlocks.

Are there built-in locks in the dicts used for managing state for loading and unloading clients? Changes to `unload_old_clients` might inadvertently compete with starting / ready client lookups?

**Comment by rwols** [comment]
I don't know. What is a strategy to debug this? This is still a fairly serious issue IMO.

**Comment by tomv564** [comment]
I narrowed down a repro where lsp-tsserver locks up when documentHighlight requests are sent to it while it is still starting up. Some additional logging might reveal if the issue persists all the way to the transport (trying TCP mode might provide some insight as well)

**Comment by rwols** [comment]
I don't experience the lockups anymore. Nice job @tomv564 and @Kronuz !
