### ISSUE TITLE
OSError: Bad path: D::\src\addobjectwindow.h

### ISSUE THREAD

**Issue by evandrocoan** [tomv564/LSP#289]
After setting up https://github.com/tomv564/LSP/issues/208 (cquery), I got this problem when using the go to definition feature:
```
2018-03-04 15:18:31,884: 6260: ERROR: can not send request; node process not running
Traceback (most recent call last):
  File "F:\SublimeText\sublime_plugin.py", line 389, in run_callback
    expr()
  File "F:\SublimeText\sublime_plugin.py", line 456, in <lambda>
    run_callback('on_close', callback, lambda: callback.on_close(v))
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\documents.py", line 205, in on_close
    Events.publish("view.on_close", view)
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\events.py", line 28, in publish
    listener(*args)
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\documents.py", line 158, in notify_did_close
    params = {"textDocument": {"uri": filename_to_uri(file_name)}}
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\url.py", line 8, in filename_to_uri
    return urljoin('file:', pathname2url(path))
  File "./python3.3/nturl2path.py", line 58, in pathname2url
OSError: Bad path: D::\src\addobjectwindow.h
```

From the error, we can see it is adding an additional colon after the `D:` letter.

```
22:00:00:000.000000 0.00e+00 - LSP.plugin.core.rpc.No Function:0 - LSP server: 2018-03-04 16:54:22.683 (  86.447s) [scan_includes]          utils.cc:319      0| Reading D:/tmp/cquery/D@@User@Dropbox@SoftwareVersioning@GraphicsComputing@src@mainwindow.cpp
16:54:22:687.258959 1.53e-03 - LSP.plugin.core.rpc.notification_handler:384 - <--  $cquery/progress
22:00:00:000.000000 0.00e+00 - LSP.plugin.core.rpc.No Function:0 - LSP server: 2018-03-04 16:54:22.683 (  86.447s) [scan_includes] clang_complete.cc:380      0| Creating completion session with arguments clang++ -working-directory=D:/User/Dropbox/SoftwareVersioning/GraphicsComputing -std=c++11 -mms-bitfields -pthread -mms-bitfields -ID:/User/Documents/msys64/mingw64/include/gtkmm-3.0 -ID:/User/Documents/msys64/mingw64/lib/gtkmm-3.0/include -ID:/User/Documents/msys64/mingw64/include/atkmm-1.6 -ID:/User/Documents/msys64/mingw64/include/gdkmm-3.0 -ID:/User/Documents/msys64/mingw64/lib/gdkmm-3.0/include -ID:/User/Documents/msys64/mingw64/include/giomm-2.4 -ID:/User/Documents/msys64/mingw64/lib/giomm-2.4/include -ID:/User/Documents/msys64/mingw64/include/pangomm-1.4 -ID:/User/Documents/msys64/mingw64/lib/pangomm-1.4/include -ID:/User/Documents/msys64/mingw64/include/glibmm-2.4 -ID:/User/Documents/msys64/mingw64/lib/glibmm-2.4/include -ID:/User/Documents/msys64/mingw64/include/gtk-3.0 -ID:/User/Documents/msys64/mingw64/include/cairo -ID:/User/Documents/msys64/mingw64/include -ID:/User/Documents/msys64/mingw64/include/pango-1.0 -ID:/User/Documents/msys64/mingw64/include/atk-1.0 -ID:/User/Documents/msys64/mingw64/include/cairo -ID:/User/Documents/msys64/mingw64/include/cairomm-1.0 -ID:/User/Documents/msys64/mingw64/lib/cairomm-1.0/include -ID:/User/Documents/msys64/mingw64/include/cairo -ID:/User/Documents/msys64/mingw64/include/pixman-1 -ID:/User/Documents/msys64/mingw64/include -ID:/User/Documents/msys64/mingw64/include/freetype2 -ID:/User/Documents/msys64/mingw64/include/libpng16 -ID:/User/Documents/msys64/mingw64/include/harfbuzz -ID:/User/Documents/msys64/mingw64/include/glib-2.0 -ID:/User/Documents/msys64/mingw64/lib/glib-2.0/include -ID:/User/Documents/msys64/mingw64/include -ID:/User/Documents/msys64/mingw64/include/freetype2 -ID:/User/Documents/msys64/mingw64/include -ID:/User/Documents/msys64/mingw64/include/harfbuzz -ID:/User/Documents/msys64/mingw64/include/libpng16 -ID:/User/Documents/msys64/mingw64/include/sigc++-2.0 -ID:/User/Documents/msys64/mingw64/lib/sigc++-2.0/include -ID:/User/Documents/msys64/mingw64/include/gdk-pixbuf-2.0 -ID:/User/Documents/msys64/mingw64/include/libpng16 -ID:/User/Documents/msys64/mingw64/include -ID:/User/Documents/msys64/mingw64/include/glib-2.0 -ID:/User/Documents/msys64/mingw64/lib/glib-2.0/include -ID:/User/Documents/msys64/mingw64/include -LD:/User/Documents/msys64/mingw64/lib -lgtkmm-3.0 -latkmm-1.6 -lgdkmm-3.0 -lgiomm-2.4 -lpangomm-1.4 -lglibmm-2.4 -lgtk-3 -lgdk-3 -lgdi32 -limm32 -lshell32 -lole32 -Wl,-luuid -lwinmm -ldwmapi -lsetupapi -lcfgmgr32 -lz -lpangowin32-1.0 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lgio-2.0 -lcairomm-1.0 -lcairo -lsigc-2.0 -lgdk_pixbuf-2.0 -lgobject-2.0 -lglib-2.0 -lintl D:/User/Dropbox/SoftwareVersioning/GraphicsComputing/src/mainwindow.cpp -resource-dir=D:/User/Documents/msys64/mingw64/lib/clang/5.0.1 -Wno-unknown-warning-option -fparse-all-comments -fspell-checking
16:54:22:688.261032 7.71e-04 - LSP.plugin.core.rpc.notification_handler:393 - Unhandled notification: $cquery/progress
22:00:00:000.000000 0.00e+00 - LSP.plugin.core.rpc.No Function:0 - LSP server: 2018-03-04 16:54:22.684 (  86.448s) [scan_includes]          utils.cc:319      0| Reading D:/tmp/cquery/D@@User@Dropbox@SoftwareVersioning@GraphicsComputing@src@mainwindow.cpp.json
22:00:00:000.000000 0.00e+00 - LSP.plugin.core.rpc.No Function:0 - LSP server: 2018-03-04 16:54:22.838 (  86.602s) [scan_includes]import_pipeline.cc:369      0| Parsing D:/User/Dropbox/SoftwareVersioning/GraphicsComputing/src/mainwindow.cpp
16:54:27:791.585922 5.12e+00 - LSP.plugin.core.main.initialize_on_open:96 - initialize on open 6 D:\User\Dropbox\SoftwareVersioning\GraphicsComputing\src\mainwindow.cpp
16:54:29:689.379930 7.00e+00 - LSP.plugin.core.rpc.send_request:268 -  --> textDocument/hover
22:00:00:000.000000 0.00e+00 - LSP.plugin.core.rpc.No Function:0 - LSP server: 2018-03-04 16:54:29.691 (  93.454s) [scan_includes]          timer.cc:35       0| [e2e] Running textDocument/hover took 0.0ms
16:54:30:356.009007 6.66e-01 - LSP.plugin.core.rpc.notification_handler:384 - <--  $cquery/progress
16:54:30:357.511997 1.73e-03 - LSP.plugin.core.rpc.notification_handler:393 - Unhandled notification: $cquery/progress
16:54:32:002.564907 1.65e+00 - LSP.plugin.core.rpc.send_request:268 -  --> textDocument/definition
22:00:00:000.000000 0.00e+00 - LSP.plugin.core.rpc.No Function:0 - LSP server: 2018-03-04 16:54:32.027 (  95.790s) [scan_includes]          timer.cc:35       0| [e2e] Running textDocument/definition took 23.22999ms
16:54:32:068.128109 6.55e-02 - LSP.plugin.core.rpc.notification_handler:384 - <--  $cquery/progress
16:54:32:069.129944 7.70e-04 - LSP.plugin.core.rpc.notification_handler:393 - Unhandled notification: $cquery/progress
16:54:32:374.418974 3.05e-01 - LSP.plugin.core.rpc.notification_handler:384 - <--  $cquery/progress
16:54:32:374.918938 7.58e-04 - LSP.plugin.core.rpc.notification_handler:393 - Unhandled notification: $cquery/progress
16:54:32:375.920057 6.90e-04 - LSP.plugin.core.rpc.notification_handler:384 - <--  $cquery/progress
16:54:32:376.419067 5.06e-04 - LSP.plugin.core.rpc.notification_handler:393 - Unhandled notification: $cquery/progress
16:54:36:679.615021 4.30e+00 - LSP.plugin.core.rpc.send_request:268 -  --> textDocument/hover
22:00:00:000.000000 0.00e+00 - LSP.plugin.core.rpc.No Function:0 - LSP server: 2018-03-04 16:54:36.681 ( 100.445s) [scan_includes]          timer.cc:35       0| [e2e] Running textDocument/hover took 0.498ms
16:54:36:887.794971 2.08e-01 - LSP.plugin.core.rpc.notification_handler:384 - <--  $cquery/progress
16:54:36:888.802052 8.24e-04 - LSP.plugin.core.rpc.notification_handler:393 - Unhandled notification: $cquery/progress
16:54:36:889.348984 7.04e-04 - LSP.plugin.core.rpc.notification_handler:384 - <--  $cquery/progress
16:54:36:889.852047 5.96e-04 - LSP.plugin.core.rpc.notification_handler:393 - Unhandled notification: $cquery/progress
16:54:43:745.250940 6.86e+00 - LSP.plugin.core.rpc.notification_handler:384 - <--  textDocument/publishDiagnostics
16:54:46:917.540073 3.17e+00 - LSP.plugin.core.rpc.send_request:268 -  --> textDocument/definition
22:00:00:000.000000 0.00e+00 - LSP.plugin.core.rpc.No Function:0 - LSP server: 2018-03-04 16:54:46.919 ( 110.683s) [scan_includes]          timer.cc:35       0| [e2e] Running textDocument/definition took 0.0ms
16:54:46:920.547962 1.81e+03 - LSP.plugin.definition.handle_response:41 - opening location {'uri': 'file:///D%3A/User/Documents/msys64/mingw64/include/gtkmm-3.0/gtkmm/box.h', 'range': {'end': {'line': 209, 'character': 17}, 'start': {'line': 209, 'character': 7}}}
16:54:46:925.048113 7.54e-03 - LSP.plugin.core.rpc.notification_handler:384 - <--  $cquery/progress
16:54:46:925.549030 6.49e-04 - LSP.plugin.core.rpc.notification_handler:393 - Unhandled notification: $cquery/progress
16:54:46:926.048994 4.83e-04 - LSP.plugin.core.rpc.notification_handler:384 - <--  $cquery/progress
16:54:46:926.548958 3.75e-04 - LSP.plugin.core.rpc.notification_handler:393 - Unhandled notification: $cquery/progress
16:54:47:279.882908 1.95e+01 - LSP.plugin.core.main.initialize_on_open:96 - initialize on open 6 D::\User\Documents\msys64\mingw64\include\gtkmm-3.0\gtkmm\box.h
Traceback (most recent call last):
  File "F:\SublimeText\sublime_plugin.py", line 417, in run_async_view_listener_callback
    vel.__class__.__dict__[name](vel)
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\documents.py", line 237, in on_load_async
    Events.publish("view.on_load_async", self.view)
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\events.py", line 28, in publish
    listener(*args)
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\documents.py", line 141, in notify_did_open
    "uri": filename_to_uri(view_file),
  File "F:\SublimeText\Data\Packages\LSP\plugin\core\url.py", line 8, in filename_to_uri
    return urljoin('file:', pathname2url(path))
  File "./python3.3/nturl2path.py", line 58, in pathname2url
OSError: Bad path: D::\User\Documents\msys64\mingw64\include\gtkmm-3.0\gtkmm\box.h
16:54:47:366.463900 8.68e-02 - LSP.plugin.core.main.initialize_on_open:96 - initialize on open 6 D::\User\Documents\msys64\mingw64\include\gtkmm-3.0\gtkmm\box.h
```

**Comment by AmjadHD** [comment]
@tomv564, this is a common issue in many LS s (ironically the LSP is implemented by Microsoft), they don't handle windows paths correctly, adding `.split('\\')` to the `uri_to_filenmae` function fixes it.

**Comment by tomv564** [comment]
Which language server is this? Ideally, Sublime, LSP and the servers agree on the conventional formatting of a path / URI of a given OS. 

If the server provides a good argument why they return lowercase drive letters then an ugly workaround is possible (massaging paths only on windows). I'd like to open a new issue if it's been taken up with the server.

**Comment by drew-wallace** [comment]
[vue-language-server](https://www.npmjs.com/package/vue-language-server)

**Comment by tomv564** [comment]
See new issue :) Thanks for reporting!
