### ISSUE TITLE
LSP with Python

### ISSUE THREAD

**Issue by gj1118** [tomv564/LSP#324]
### Question:
I am trying to set up LSP for python, but it does not work for me. I have setup the LSP server , but when I choose the option to start the server from ST , it never complains about not being able to start it. Since it never complains, I assume that it was able to start it.

I am using on a Mac 10.13.4 (17E202), running Sublime Text 3174

Here is what I have done till now.

```pip install python-language-server```
Installed the LSP plugin for ST
opened a Python file
Pressed CMD+SHIFT+P to choose Enable language server globally
Here is what I see in the logs (I can see that there are some errors)

```LSP: global clients: jsts=True
Package Control: Skipping automatic upgrade, last run at 2018-05-11 22:31:08, next run at 2018-05-11 23:31:08 or after
LSP: global clients: pyls=True, jsts=True
reloading settings Packages/User/LSP.sublime-settings
LSP: global clients: pyls=True, jsts=True
reloading settings Packages/User/LSP.sublime-settings
LSP: global clients: pyls=True, jsts=True
reloading settings Packages/User/LSP.sublime-settings
LSP: global clients: pyls=True, jsts=True
reloading settings Packages/User/LSP.sublime-settings
LSP: global clients: pyls=True, jsts=True
reloading settings Packages/User/LSP.sublime-settings
LSP: global clients: pyls=True, jsts=True
reloading settings Packages/User/LSP.sublime-settings
LSP: global clients: pyls=True, jsts=True
LSP: global clients: pyls=False, jsts=True
Traceback (most recent call last):
File "/Users/gjanjua/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/configuration.py", line 81, in <lambda>
File "/Users/gjanjua/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/clients.py", line 170, in unload_window_clients
File "/Users/gjanjua/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/clients.py", line 211, in unload_client
AttributeError: 'NoneType' object has no attribute 'send_request'
reloading settings Packages/User/LSP.sublime-settings
LSP: global clients: pyls=False, jsts=True
LSP: global clients: pyls=True, jsts=True
reloading settings Packages/User/LSP.sublime-settings
LSP: global clients: pyls=True, jsts=True
ignored packages updated to: ["Jedi - Python autocompletion", "Vintage"]
unloading plugin Jedi - Python autocompletion.__init__
reloading settings Packages/Jedi - Python autocompletion/sublime_jedi.sublime-settings
generating meta info summary
reloading settings Packages/User/Preferences.sublime-settings
ignored packages updated to: ["Vintage"]
reloading plugin Jedi - Python autocompletion.__init__
reloading settings Packages/Jedi - Python autocompletion/sublime_jedi.sublime-settings
generating meta info summary
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/LSP.sublime-settings
LSP: global clients: pyls=True, jsts=True
reloading settings Packages/User/LSP.sublime-settings
LSP: global clients: pyls=True, jsts=True
```

Can you please let me know what is the wrong thing that I am doing here ?

**Comment by tomv564** [comment]
It looks like LSP _would_ find an enabled pyls config, but I don't see any attempt to start the server in your logs. Since this log contains so many config changes, could you share logs from a newly started editor, opening a python file?
