### ISSUE TITLE
Renaming a symbol with pyls errors

### ISSUE THREAD

**Issue by slice** [tomv564/LSP#329]
**OS:** macOS
**Language Server:** pyls
**Installation:** Git

## Reproduction steps

* Right click on a symbol
* Click "Rename"
* Type a name
* Press enter

## Traceback

```py
Traceback (most recent call last):
  File "/Users/slice/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/core/rpc.py", line 322, in receive_payload
    self.response_handler(payload)
  File "/Users/slice/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/core/rpc.py", line 341, in response_handler
    self._response_handlers[handler_id](result)
  File "/Users/slice/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/rename.py", line 35, in handle_response
    if 'changes' in response:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by tomv564** [comment]
Thanks for reporting, hope to include this fix in a proper fix soon!

**Comment by slice** [comment]
Ah, thanks! What caused this was that I installed the wrong build of `python-language-server`. Doing `pip3 install 'python-language-server[all]'` helped.
