### ISSUE TITLE
Trying tsserver.js (for TypeScript)

### ISSUE THREAD

**Issue by Kronuz** [tomv564/LSP#336]
### Bug:

I tried using the tsserver.js from TypeScript package, but apparently we are missing something about the protocol?

I'm getting an error about it not understanding command "Content-Length: 830". Any idea what could be going on?

```
Info 0    [17:11:20.235] Starting TS Server
Info 1    [17:11:20.236] Version: 2.9.1
Info 2    [17:11:20.236] Arguments: /usr/local/Cellar/node/9.11.1/bin/node /Users/kronuz/Library/Application Support/Sublime Text 3/Packages/TypeScript/tsserver/tsserver.js --disableAutomaticTypingAcquisition
Info 3    [17:11:20.236] Platform: darwin NodeVersion: 9 CaseSensitive: false
Info 4    [17:11:20.240] Provided types map file "/Users/kronuz/Library/Application Support/Sublime Text 3/Packages/TypeScript/tsserver/tsserver.js/../typesMap.json" doesn't exist
Info 5    [17:11:20.244] request:
    Content-Length: 830
Err 6     [17:11:20.259] Exception on executing command Content-Length: 830:

    Unexpected token C in JSON at position 0

    SyntaxError: Unexpected token C in JSON at position 0
    at JSON.parse (<anonymous>)
    at IOSession.Session.onMessage (/Users/kronuz/Library/Application Support/Sublime Text 3/Packages/TypeScript/tsserver/tsserver.js:97249:36)
    at Interface.<anonymous> (/Users/kronuz/Library/Application Support/Sublime Text 3/Packages/TypeScript/tsserver/tsserver.js:98456:27)
    at Interface.emit (events.js:180:13)
    at Interface._onLine (readline.js:285:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:144:10)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at Pipe.onread (net.js:581:20)
```

**Comment by Kronuz** [comment]
Nevermind... reading more, it seems tsserver isn't using language server protocol. There is a wrapper though: https://github.com/theia-ide/typescript-language-server

**Comment by tomv564** [comment]
Correct, I also sort-of maintain a wrapper: http://github.com/tomv564/lsp-tsserver
