### ISSUE TITLE
Restart server command is broken

### ISSUE THREAD

**Issue by AmjadHD** [tomv564/LSP#343]
When invoking the restart server command, this happens:

```python
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1072, in run_
    return self.run(edit)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/main.py", line 391, in run
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/main.py", line 367, in restart_window_clients
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/clients.py", line 170, in unload_window_clients
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/clients.py", line 211, in unload_client
AttributeError: 'NoneType' object has no attribute 'send_request'
```

**Comment by tomv564** [comment]
Have seen this bug for a while, re-opening the view is a possible workaround? But yes, must be fixed.

**Comment by tomv564** [comment]
Shutdown has been rewritten, `unload_client` no longer exists so hopefully the error is gone, too

**Comment by AmjadHD** [comment]
no @tomv564 , it's still there, the error is gone though, but it still doesn't restart the server.
