### ISSUE TITLE
LSP with Elixir

### ISSUE THREAD

**Issue by smanolloff** [tomv564/LSP#347]
Hello,

I am opening this issue, although I found #305, but I don't get the same error.

I am trying to use JakeBecker's [ElixirLS](https://github.com/JakeBecker/elixir-ls), but could not make it work. I see no errors in the console whatsoever, would you please help me understand what is going on?

* macOS 10.13.2
* SublimeText 3.1.1 (3176)
* LSP 0.6.0, installed via Package Control
* Package configuration:
```json
{
  "log_payloads": true,
  "log_debug": true,
  "show_diagnostics_severity_level": 4,
  "clients": {
    "elixir": {
      "command": ["/Users/simo/Projects/elixir-ls/language_server.sh"],
      "enabled": true,
      "languageId": "elixir",
      "scopes": ["source.elixir"],
      "syntaxes": ["Packages/Elixir/Syntaxes/Elixir.tmLanguage"]
    }
  }
}

```
* Sublime console log:
```
startup, version: 3176 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/simo/Library/Application Support/Sublime Text 3/Packages
state path: /Users/simo/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/simo/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["GitGutter", "SublimeLinter", "SublimeLinter-contrib-elixirc", "SublimeLinter-contrib-eslint_d", "SublimeLinter-flake8", "SublimeLinter-ruby", "Vintage"]
pre session restore time: 0.32169
using gpu buffer for window
startup time: 0.424931
environment variables loaded using: /bin/zsh -l
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
(...)
plugins loaded
LSP: window has override for elixir {'enabled': True}
LSP: starting active= /Users/simo/work/Projects/moneyflow/lib/moneyflow.ex other= 0
LSP: initialize on open 2 /Users/simo/work/Projects/moneyflow/lib/moneyflow.ex
LSP: starting in /Users/simo/work/Projects/moneyflow
LSP: starting ['/Users/simo/Projects/elixir-ls/language_server.sh']
LSP:  --> initialize
reloading settings Packages/User/Mediawiker.sublime-settings
LSP: initialize on open 2 /Users/simo/work/Projects/moneyflow/lib/moneyflow.ex
LSP: Already starting on this window: elixir
LSP: LSP stdout process ended.
Package Control: Skipping automatic upgrade, last run at 2018-06-21 14:08:55, next run at 2018-06-21 15:08:55 or after
LSP: initialize on open 2 /Users/simo/work/Projects/moneyflow/lib/moneyflow.ex
LSP: Already starting on this window: elixir
LSP: elixir in state 0  for view /Users/simo/work/Projects/moneyflow/lib/moneyflow.ex in window 2
LSP: elixir in state 0  for view /Users/simo/work/Projects/moneyflow/lib/moneyflow.ex in window 2
LSP: elixir in state 0  for view /Users/simo/work/Projects/moneyflow/lib/moneyflow.ex in window 2
(...)
```

And nothing seems to happen. Just the `LSP: Already starting on this window: elixir` and `LSP: initialize on open 2 /Users/simo/work/Projects/moneyflow/lib/moneyflow.ex` occasionally repeating in the logs, but no errors or any other activity whatsoever.

"Restart servers" command throws the error already reported in #343, so it doesn't help.

Running ElixirLS manually from terminal looks good: it starts up and waits for input:
```json
$ /Users/simo/Projects/elixir-ls/language_server.sh   
Content-Length: 101

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Started ElixirLS\n","type":4}}
```

Is there a way to at least further increase logging for the LSP plugin, as I just can't understand where  the actual problem is :(

Thank you in advance!

**Comment by tomv564** [comment]
It looks like the server shuts down after receiving the initialize notification. See “stdout process ended”.

Try checking the server logs or enable ‘log_stderr’ in case the server logs there ?

**Comment by smanolloff** [comment]
Great, I restarted the machine and now it works as expected... :) Restarting sublime before that sure did not help, guess it was something OS-specific. I can't reproduce this anymore, so I will close this.

Thank you for your prompt reply 🍺

**Comment by laibulle** [comment]
on my side I get 

```
LSP: window 2 requests elixir for /Users/laibulle/Projects/bonsai/bonsai/lib/bonsai_web/views/login_view.ex
LSP: starting in /Users/laibulle/Projects/bonsai/bonsai
LSP: starting ['/Users/simo/Projects/elixir-ls/language_server.sh']
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 490, in run_async_view_listener_callback
    vel.__class__.__dict__[name](vel)
  File "/Users/laibulle/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/documents.py", line 83, in on_activated_async
    global_events.publish("view.on_activated_async", self.view)
  File "/Users/laibulle/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/events.py", line 26, in publish
    listener(*args)
  File "/Users/laibulle/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/main.py", line 52, in on_view_activated
    windows.lookup(window).activate_view(view)
  File "/Users/laibulle/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 349, in activate_view
    self._initialize_on_open(view)
  File "/Users/laibulle/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 358, in _initialize_on_open
    self._start_client(config)
  File "/Users/laibulle/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 389, in _start_client
    if session:
UnboundLocalError: local variable 'session' referenced before assignment
```

**Comment by smanolloff** [comment]
@laibulle you can't use the _same_ config -- the path to the elixir-ls executable itself is wrong for your machine:
`/Users/simo/Projects/elixir-ls/language_server.sh`

You need to install elixir ls and change the path accordingly...

**Comment by laibulle** [comment]
Oh, indeed ^^. 
It works much better now. 

But did you manage to get auto formatter working @smanolloff ? It doesn't work on my side.

**Comment by tomv564** [comment]
It's unfortunate that the path to the server is the only thing that makes the Elixir configs not shareable. 

I'd love to add it (with a default command of "elixir_ls") to LSP's built-in configs. Is there a way to install it so it's available on the PATH? Something like `mix install.archive github.com/JakeBecker/elixir-ls` ?
