### ISSUE TITLE
Unknown `CompletionItemKind`s are not handled properly

### ISSUE THREAD

**Issue by LaurentTreguier** [tomv564/LSP#348]
### Bug:
As it stands now, this LSP client specifies which `CompletionItemKind`s it supports in `TextDocumentClientCapabilities `. [According to the spec](https://microsoft.github.io/language-server-protocol/specification#initialize), if `InitializeParams.capabilities.textDocument.completion.completionItemKind.valueSet` is set, the client also guarantees that any value outside of `valueSet` will be handled gracefully and fall back to a default value:
```typescript
completionItemKind?: {
	/**
	 * The completion item kind values the client supports. When this
	 * property exists the client also guarantees that it will
	 * handle values outside its set gracefully and falls back
	 * to a default value when unknown.
	 *
	 * If this property is not present the client only supports
	 * the completion items kinds from `Text` to `Reference` as defined in
	 * the initial version of the protocol.
	 */
	valueSet?: CompletionItemKind[];
},
```
However, this is not the case here, the client emits an error instead of handling the unknown value:
```
Error handling server payload
Traceback (most recent call last):
  File "C:\Users\laure\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/rpc.py", line 322, in receive_payload
    self.response_handler(payload)
  File "C:\Users\laure\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/rpc.py", line 341, in response_handler
    self._response_handlers[handler_id](result)
  File "C:\Users\laure\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/completion.py", line 261, in handle_response
    self.completions = list(self.format_completion(item) for item in items)
  File "C:\Users\laure\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/completion.py", line 261, in <genexpr>
    self.completions = list(self.format_completion(item) for item in items)
  File "C:\Users\laure\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/completion.py", line 237, in format_completion
    hint = completion_item_kind_names[kind]
KeyError: 19
```
This fallback behavior is also mandatory for `InitializeParams.capabilities.workspace.symbol.symbolKind.valueSet` and `InitializeParams.capabilities.textDocument.documentSymbol.symbolKind.valueSet`, although I haven't tested them in this client yet, so I don't know if they are affected as well.

**Comment by gobijan** [comment]
@tomv564 once upon a time my python was strong.. I could have a look and see what I can do if you give me some hints what needs to be done? I'm eager to get it working with Ruby/Rails ;D
