### ISSUE TITLE
Add Ruby / Ruby on Rails Support

### ISSUE THREAD

**Issue by gobijan** [tomv564/LSP#354]
Hi as stated in the docs I am creating this issue to start discussions about adding Ruby support.

There is https://github.com/castwide/solargraph available as ruby language server.
Any plans on enabling this?

**Comment by tomv564** [comment]
Hi, someone was trying it on April 11th in the gitter channel: https://gitter.im/SublimeLSP/Lobby
The configuration posted there should be a good starting point.
If it works for you, then we can add a config and instructions to our documentation for future users.

**Comment by gobijan** [comment]
I worked out the following config supporting Ruby and Rails:

```
{
	"clients":
	{
		"ruby":
		{
			"command":
			[
				"solargraph",
				"socket"
			],
			"enabled": true,
			"languageId": "ruby",
			"scopes":
			[
				"source.ruby",
				"source.ruby.rails"
			],
			"syntaxes":
			[
				"Packages/Ruby/Ruby.sublime-syntax",
				"Packages/Rails/Ruby on Rails.sublime-syntax"
			]
		}
	}
}
```

Autocompletion does not work even though the language server (solargraph) seems to be started correctly.
These are my debug logs (log_debug and log_stderr both set to true):

```
LSP: initialize on open 3 /Users/bijan/dev/ruby/subscription-app/app/controllers/home_controller.rb
LSP: starting in /Users/bijan/dev/ruby/subscription-app
LSP: starting ['solargraph', 'socket']
LSP:  --> initialize
LSP: initialize on open 3 /Users/bijan/dev/ruby/subscription-app/app/controllers/home_controller.rb
LSP: Already starting on this window: ruby
server: Solargraph is listening PORT=7658 PID=4131
LSP: ruby in state 0  for view /Users/bijan/dev/ruby/subscription-app/app/controllers/home_controller.rb in window 3
LSP: ruby in state 0  for view /Users/bijan/dev/ruby/subscription-app/app/controllers/home_controller.rb in window 3
LSP: ruby in state 0  for view /Users/bijan/dev/ruby/subscription-app/app/controllers/home_controller.rb in window 3
no command for selector: noop:
no command for selector: noop:
no command for selector: noop:
no command for selector: noop:
no command for selector: noop:
LSP: initialize on open 3 /Users/bijan/dev/ruby/subscription-app/app/controllers/home_controller.rb
LSP: Already starting on this window: ruby
ApplySyntax: Syntax already set to Packages/Rails/Ruby on Rails.sublime-syntax
ApplySyntax: Syntax set to Ruby on Rails using Packages/Rails/Ruby on Rails.sublime-syntax
LSP: initialize on open 3 /Users/bijan/dev/ruby/subscription-app/app/models/publication.rb
LSP: Already starting on this window: ruby
LSP: initialize on open 3 /Users/bijan/dev/ruby/subscription-app/app/models/publication.rb
LSP: Already starting on this window: ruby
LSP: ruby in state 0  for view /Users/bijan/dev/ruby/subscription-app/app/models/publication.rb in window 3
LSP: ruby in state 0  for view /Users/bijan/dev/ruby/subscription-app/app/models/publication.rb in window 3
LSP: ruby in state 0  for view /Users/bijan/dev/ruby/subscription-app/app/models/publication.rb in window 3
ApplySyntax: Syntax already set to Packages/Rails/Ruby on Rails.sublime-syntax
```

Any idea what could be broken?

**Comment by tomv564** [comment]
Same as in the gitter discussion, your config is not telling LSP to use TCP
(stdio is the default)

Add `”tcp_port”: 7658 ` to the client config?

We do need better logging / a time-out when stdio fails to initialize

**Comment by gobijan** [comment]
Okay now I get some completion results.
Unfortunately they seem to be very fragile. It has throws this error sometimes:

```
LSP: socket send
Error handling server payload
Traceback (most recent call last):
  File "/Users/bijan/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/rpc.py", line 322, in receive_payload
    self.response_handler(payload)
  File "/Users/bijan/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/rpc.py", line 341, in response_handler
    self._response_handlers[handler_id](result)
  File "/Users/bijan/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/completion.py", line 261, in handle_response
    self.completions = list(self.format_completion(item) for item in items)
  File "/Users/bijan/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/completion.py", line 261, in <genexpr>
    self.completions = list(self.format_completion(item) for item in items)
  File "/Users/bijan/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/completion.py", line 237, in format_completion
    hint = completion_item_kind_names[kind]
KeyError: 21
```

I'll take a short video.

**Comment by tomv564** [comment]
That is a recently found issue with LSP: https://github.com/tomv564/LSP/issues/348
Thanks for sharing logs, if we fix the above do you mind trying again ?

**Comment by gobijan** [comment]
Sure of course just let me know :)

**Comment by tomv564** [comment]
The needed fix from completion item kinds is in in master, but not yet released.
You can either wait for a release, or add this repo as a Package Control Repository in Sublime Text and run LSP from master instead.

**Comment by gobijan** [comment]
Great the master version kind of now works for me now.
VSCode offers "Search Ruby Documentation". Is this something that can be done too or is it currently not implemented?
 
Here is a screenshot of the thing working: 
<img width="1278" alt="bildschirmfoto 2018-06-27 um 10 03 31" src="https://user-images.githubusercontent.com/49339/41960977-7092d6ee-79f1-11e8-949a-ae41e7facfd3.png">

**Comment by tomv564** [comment]
Nice color scheme, good to see the tooltips look ok with your setup!

"Search $YOUR_LANGUAGE documentation" is a pretty powerful feature, the language server protocol doesn't specify a way for all languages to provide the feature consistently.

This is the kind of thing Dash does well, or someone could add the feature via an LSP-ruby package
