### ISSUE TITLE
KeyError from open_after_initialize_by_window

### ISSUE THREAD

**Issue by Kronuz** [tomv564/LSP#362]
### Bug:

I often keep getting this weird traceback in the console:

```python
LSP: javascript-typescript client registered for window 5
Error handling server payload
Traceback (most recent call last):
  File "/Users/kronuz/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/core/rpc.py", line 176, in receive_payload
    self.response_handler(payload)
  File "/Users/kronuz/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/core/rpc.py", line 195, in response_handler
    self._response_handlers[handler_id](result)
  File "/Users/kronuz/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/core/main.py", line 317, in <lambda>
    lambda result: handle_initialize_result(result, client, window, project_path, config))
  File "/Users/kronuz/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/core/main.py", line 177, in handle_initialize_result
    for view in open_after_initialize_by_window[window.id()]:
KeyError: 5
```

Any ideas?

**Comment by tomv564** [comment]
Yes, is it when restarting the language server or on initial startup?

When starting up, LSP saves the currently active view(s) to be sent to the server after initialization in `open_after_initialize_by_window`. In your case, this "open after initialise" list no longer contains the window id that has triggered initialisation.

**Comment by tomv564** [comment]
This error was one of the reasons why recent code in master keeps more state at the window level.
I think it might be fixed, or the error will simply look different. 

Thanks for reporting, if it happens again would need a bit more context on what was being done.
