### ISSUE TITLE
Receiving AssertionError: must have a panel now!

### ISSUE THREAD

**Issue by Kronuz** [tomv564/LSP#363]
### Bug:

I often keep getting this weird traceback in the console:

```python
Error handling notification textDocument/publishDiagnostics
Traceback (most recent call last):
  File "/Users/kronuz/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/core/rpc.py", line 238, in notification_handler
    self._notification_handlers[method](params)
  File "/Users/kronuz/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/core/main.py", line 144, in <lambda>
    lambda params: handle_client_diagnostics(window, config.name, params))
  File "/Users/kronuz/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/core/diagnostics.py", line 55, in handle_client_diagnostics
    Events.publish("document.diagnostics", DiagnosticsUpdate(window, client_name, file_path, diagnostics))
  File "/Users/kronuz/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/core/events.py", line 28, in publish
    listener(*args)
  File "/Users/kronuz/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/diagnostics.py", line 202, in <lambda>
    lambda update: handle_diagnostics(update))
  File "/Users/kronuz/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/diagnostics.py", line 213, in handle_diagnostics
    update_diagnostics_panel(window)
  File "/Users/kronuz/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/diagnostics.py", line 279, in update_diagnostics_panel
    assert panel, "must have a panel now!"
AssertionError: must have a panel now!
```

Any ideas?

**Comment by Kronuz** [comment]
I have a JSON server running, and it's using jsonc for Sublime Text Settings. When I go into the preferences (<kbd>⌘</kbd>+<kbd>,</kbd>) it opens a new window with two panels (default + user settings) and when I close the settings it closes the window and I get this assertion ***every time***.

**Comment by Kronuz** [comment]
The following is what I see in the console when closing the settings window with all logs active; apparently, the server it's sending a `textDocument/publishDiagnostics` ***after*** it received a `textDocument/didClose` (and after the panel has been closed) and it breaks when such diagnostics are being handled:

```
LSP: initialize on open 3 /Users/kronuz/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings
LSP: Couldn't determine project directory since no folders are open! Using /Users/kronuz/Library/Application Support/Sublime Text 3/Packages/User as a fallback.
LSP:  >>> textDocument/didClose
LSP:  --> {'textDocument': {'uri': 'file:///Users/kronuz/Library/Application%20Support/Sublime%20Text%203/Packages/User/Preferences.sublime-settings'}}
LSP: Couldn't determine project directory since no folders are open! Using /Users/kronuz/Library/Application Support/Sublime Text 3/Packages/Default as a fallback.
LSP:  <<< textDocument/publishDiagnostics
LSP:  <-- {'diagnostics': [], 'uri': 'file:///Users/kronuz/Library/Application%20Support/Sublime%20Text%203/Packages/User/Preferences.sublime-settings'}
LSP:  >>> textDocument/didClose
LSP:  --> {'textDocument': {'uri': 'file:///Users/kronuz/Library/Application%20Support/Sublime%20Text%203/Packages/Default/Preferences.sublime-settings'}}
LSP: Couldn't determine project directory since no folders are open and the current file isn't saved on the disk.
LSP: No view is active in current window
Error handling notification textDocument/publishDiagnostics
Traceback (most recent call last):
  File "/Users/kronuz/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/core/rpc.py", line 256, in notification_handler
    self._notification_handlers[method](params)
  File "/Users/kronuz/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/core/main.py", line 144, in <lambda>
    lambda params: handle_client_diagnostics(window, config.name, params))
  File "/Users/kronuz/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/core/diagnostics.py", line 55, in handle_client_diagnostics
    Events.publish("document.diagnostics", DiagnosticsUpdate(window, client_name, file_path, diagnostics))
  File "/Users/kronuz/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/core/events.py", line 28, in publish
    listener(*args)
  File "/Users/kronuz/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/diagnostics.py", line 202, in <lambda>
    lambda update: handle_diagnostics(update))
  File "/Users/kronuz/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/diagnostics.py", line 213, in handle_diagnostics
    update_diagnostics_panel(window)
  File "/Users/kronuz/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/diagnostics.py", line 279, in update_diagnostics_panel
    assert panel, "must have a panel now!"
AssertionError: must have a panel now!

LSP:  <<< textDocument/publishDiagnostics
LSP:  <-- {'diagnostics': [], 'uri': 'file:///Users/kronuz/Library/Application%20Support/Sublime%20Text%203/Packages/Default/Preferences.sublime-settings'}
LSP: No view is active in current window
Error handling notification textDocument/publishDiagnostics
Traceback (most recent call last):
  File "/Users/kronuz/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/core/rpc.py", line 256, in notification_handler
    self._notification_handlers[method](params)
  File "/Users/kronuz/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/core/main.py", line 144, in <lambda>
    lambda params: handle_client_diagnostics(window, config.name, params))
  File "/Users/kronuz/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/core/diagnostics.py", line 55, in handle_client_diagnostics
    Events.publish("document.diagnostics", DiagnosticsUpdate(window, client_name, file_path, diagnostics))
  File "/Users/kronuz/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/core/events.py", line 28, in publish
    listener(*args)
  File "/Users/kronuz/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/diagnostics.py", line 202, in <lambda>
    lambda update: handle_diagnostics(update))
  File "/Users/kronuz/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/diagnostics.py", line 213, in handle_diagnostics
    update_diagnostics_panel(window)
  File "/Users/kronuz/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/diagnostics.py", line 279, in update_diagnostics_panel
    assert panel, "must have a panel now!"
AssertionError: must have a panel now!

LSP: window closed 3
LSP: unloading client json <LSP.plugin.core.rpc.Client object at 0x10c8d6910>
LSP:  >>> shutdown
LSP:  <-- None
LSP:  >>> exit
LSP: all clients unloaded
LSP: clients for window 3 unloaded
LSP: LSP: LSP stdout process ended.
LSP stream logger stopped.
```
