### ISSUE TITLE
TypeError: 'NoneType' object is not iterable when trying to use LSP with python

### ISSUE THREAD

**Issue by spooky** [tomv564/LSP#379]
tried both the stable package release as well as cloning master. When I enable LSP for python (and try to format document) I get:
```
Traceback (most recent call last):
  File "D:\tools\sublime\sublime_plugin.py", line 1066, in run_
    return self.run(edit, **args)
  File "C:\Users\spooky\AppData\Roaming\Sublime Text 3\Packages\LSP\plugin\core\edit.py", line 62, in run
    changes = self.changes_sorted(changes)
  File "C:\Users\spooky\AppData\Roaming\Sublime Text 3\Packages\LSP\plugin\core\edit.py", line 114, in changes_sorted
    return sorted(changes, key=get_start_position)
TypeError: 'NoneType' object is not iterable
```
full log:
```

LSP: initialize on open 2 C:\Users\spooky\Desktop\foo.py
LSP: Couldn't determine project directory since no folders are open! Using C:\Users\spooky\Desktop as a fallback.
LSP: Couldn't determine project directory since no folders are open! Using C:\Users\spooky\Desktop as a fallback.
LSP: Already starting on this window: pyls
LSP:  --> initialized
LSP:  --> textDocument/didOpen
LSP: <--  textDocument/publishDiagnostics
LSP: Couldn't determine project directory since no folders are open! Using C:\Users\spooky\Desktop as a fallback.
Package Control: Skipping automatic upgrade, last run at 2018-07-21 19:10:19, next run at 2018-07-21 20:10:19 or after
LSP:  --> textDocument/hover
LSP: initialize on open 2 C:\Users\spooky\Desktop\foo.py
LSP: Couldn't determine project directory since no folders are open! Using C:\Users\spooky\Desktop as a fallback.
LSP:  --> textDocument/documentHighlight
LSP:  --> textDocument/documentHighlight
LSP:  --> textDocument/formatting
Traceback (most recent call last):
  File "D:\tools\sublime\sublime_plugin.py", line 1066, in run_
    return self.run(edit, **args)
  File "C:\Users\spooky\AppData\Roaming\Sublime Text 3\Packages\LSP\plugin\core\edit.py", line 62, in run
    changes = self.changes_sorted(changes)
  File "C:\Users\spooky\AppData\Roaming\Sublime Text 3\Packages\LSP\plugin\core\edit.py", line 114, in changes_sorted
    return sorted(changes, key=get_start_position)
TypeError: 'NoneType' object is not iterable

```

using sublime 3.1.1 build 3176, python 3.7.0, python-language-server 0.19.0

Doc highlights (squiggly errors) don't work as well, but the on hover docs do, go to definition as well.

**Comment by tomv564** [comment]
This is probably another example of the bugs introduced when the protocol suddenly decided to allow null responses :( 

Besides fixing that in the format response handler, your real issue might be that pyls has no formatter enabled / installed. You might have to look closely how it is currently is installed, I also lost formatting support with a recent update.

Good to hear that some features work. As LSP is hinting in your logs, some things may work better when editing files from a folder added to your Sublime project.

**Comment by otto-md** [comment]
I ran into the same issue today while formatting one of my go files using https://github.com/sourcegraph/go-langserver. Other go files are formatted as expected.

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1066, in run_
    return self.run(edit, **args)
  File "/Users/ottob/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/edit.py", line 47, in run
  File "/Users/ottob/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/edit.py", line 99, in changes_sorted
TypeError: 'NoneType' object is not iterable
```

Should this be reported to the go-langserver project?

**Comment by tomv564** [comment]
@otto-md the go-langserver maintainers might be interested in an edge case, but the language server is fully in its right to send "null" changes when there are none (perhaps your example document is already formatted?)

Fix for LSP has been pushed to master.
