### ISSUE TITLE
Pyls doesn't work

### ISSUE THREAD

**Issue by AmjadHD** [tomv564/LSP#514]
* OS and language server: Windows 10, pyls 0.20
* Sublime Text: 3189
* How you installed LSP (Package Control or from git?): Package Control
* Minimal reproduction steps
1- open a python file
* Configurations
```json
		"pyls":
		{
			"command":
			[
				"pyls"
			],
			"enabled": true,
			"languageId": "python",
			"settings": {
				"pyls": {
					"configurationSources": ["flake8"],
					"plugins": {
						"pyflakes": {
							"enabled": false
						}
					},
				}
			},
			"scopes":
			[
				"source.python"
			],
			"syntaxes":
			[
				"Python"
			]
		},
```
* Log
```
LSP: global configs ['vscode-html=True', 'vscode-json=True', 'lsp-tsserver=True', 'eslint=False', 'phpls=False', 'bashls=True', 'javascript-typescript-langserver=False', 'rls=True', 'haskell-ide-engine=False', 'clangd=False', 'ocaml=False', 'golsp=False', 'mspyls=False', 'reason=False', 'typescript-language-server=False', 'polymer-ide=False', 'jdtls=True', 'vscode-css=True', 'julials=False', 'pyls=True', 'cquery=False', 'kotlinls=True']
LSP: window 2 starting 1 initial views
LSP: window 2 requests pyls for D:\Amjad\sublime-edit-settings\settings.py
LSP: starting in D:\Amjad\sublime-edit-settings
LSP: starting ['pyls']
LSP:  --> initialize
LSP: window 2 added session pyls
server: Traceback (most recent call last):
server: File "C:\Users\Lehdhili\AppData\Local\Programs\Python\Python37\Scripts\pyls-script.py", line 11, in <module>
server: load_entry_point('python-language-server==0.20.0', 'console_scripts', 'pyls')()
server: File "c:\users\lehdhili\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
server: return get_distribution(dist).load_entry_point(group, name)
server: File "c:\users\lehdhili\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 2793, in load_entry_point
server: return ep.load()
server: File "c:\users\lehdhili\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 2411, in load
server: return self.resolve()
server: File "c:\users\lehdhili\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 2417, in resolve
server: module = __import__(self.module_name, fromlist=['__name__'], level=0)
server: File "c:\users\lehdhili\appdata\local\programs\python\python37\lib\site-packages\pyls\__main__.py", line 7, in <module>
server: from .python_ls import start_io_lang_server, start_tcp_lang_server, PythonLanguageServer
server: File "c:\users\lehdhili\appdata\local\programs\python\python37\lib\site-packages\pyls\python_ls.py", line 5, in <module>
server: from jsonrpc.dispatchers import MethodDispatcher
server: ModuleNotFoundError: No module named 'jsonrpc.dispatchers'
LSP: LSP stream logger stopped.
LSP: LSP stdout process ended.
```

**Comment by tomv564** [comment]
Why open an issue with pyls here? Please report server problems at their repo: https://github.com/palantir/python-language-server/issues
