### ISSUE TITLE
Intelephense v1.0 released with a few issues

### ISSUE THREAD

**Issue by carlevison** [tomv564/LSP#517]
I'm happy to announce Intelephense v1.0 is released. More info can be found [here](https://github.com/bmewburn/intelephense-docs)

I'm not entirely sure if this is an LSP issue or a server issue.

When autocompleting method names I have to manually type the parenthesis and tooltip information seems messed up.

![tooltip](https://i.imgur.com/ITBEn6a.png)

* OSX 10.14 - Intelephense 1.0
* Package Control

**Comment by jfcherng** [comment]
Would you mind share me your LSP config?

Mine is as below but it failed to start.

```javascript
"intelephense-ls":
{
    // https://github.com/bmewburn/intelephense-docs
    // npm -g i intelephense
    // yarn global add intelephense
    "enabled": true,
    "command": [
        "node",
        // "C:/Users/Clover/AppData/Roaming/npm/intelephense",
        "C:/Users/Clover/AppData/Local/Yarn/bin/intelephense",
        "--stdio",
    ],
    "scopes": ["source.php", "embedding.php"],
    "syntaxes": ["Packages/PHP/PHP.sublime-syntax"],
    "languageId": "php",
    "initializationOptions": {
        "storagePath": "C:/Users/Clover/AppData/Local/Temp/intelephense-ls",
    },
},
```

## Full error log

```
LSP: global configs ['rls=False', 'javascript-typescript-langserver=False', 'polymer-ide=False', 'cquery=True', 'lsp-tsserver=False', 'golsp=False', 'typescript-language-server=False', 'clangd=False', 'pyls=True', 'reason=False', 'intelephense-ls=True', 'phpls=False', 'haskell-ide-engine=False', 'eslint=False', 'ocaml=False', 'jdtls=False']
LSP: window 2 starting 1 initial views
LSP: window 2 requests intelephense-ls for E:\xxx.php
LSP: starting in E:\WWW\FanHuaJi_Backend
LSP: starting ['node', 'C:/Users/Clover/AppData/Local/Yarn/bin/intelephense', '--stdio']
LSP:  --> initialize
LSP: window 2 added session intelephense-ls
server: C:\Users\Clover\AppData\Local\Yarn\bin\intelephense:2
server: basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
server: ^^^^^^^
server: 
server: SyntaxError: missing ) after argument list
server: at new Script (vm.js:79:7)
server: at createScript (vm.js:251:10)
server: at Object.runInThisContext (vm.js:303:10)
server: at Module._compile (internal/modules/cjs/loader.js:657:28)
server: at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
server: at Module.load (internal/modules/cjs/loader.js:599:32)
server: at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
server: at Function.Module._load (internal/modules/cjs/loader.js:530:3)
server: at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
server: at startup (internal/bootstrap/node.js:283:19)
LSP: LSP stream logger stopped.
LSP: LSP stdout process ended.
```

**Comment by carlevison** [comment]
Hey pal,

Sorry been out and only just got back. Have you got this working?

**Comment by jfcherng** [comment]
Yes. I have made it work. It still have some tiny problem though.

But it’s running. 😊

**Comment by jfcherng** [comment]
For people who want to try this new v1.0 PHP Intelephense LSP, I have it run with the following config.

I mean, just only running. There are still some other problems you may encounter like the OP here.

```javascript
"intelephense":
{
    // https://github.com/bmewburn/intelephense-docs
    // npm -g i intelephense
    // yarn global add intelephense
    "enabled": false,
    "command": [
        "node",
        // "C:/Users/Clover/AppData/Roaming/npm/node_modules/intelephense/lib/intelephense.js",
        "C:/Users/Clover/AppData/Local/Yarn/Data/global/node_modules/intelephense/lib/intelephense.js",
        "--stdio",
    ],
    "scopes": ["source.php", "embedding.php"],
    "syntaxes": ["Packages/PHP/PHP.sublime-syntax"],
    "languageId": "php",
    "initializationOptions": {
        "storagePath": "C:/Users/Clover/AppData/Local/Temp/intelephense-ls",
    },
},
```

**Comment by carlevison** [comment]
v1.0.2 is the latest version of Intelephense, you can upgrade to the latest version by running this command.

```npm upgrade -g intelephense```

**Comment by jfcherng** [comment]
After upgrading to v1.0.2, I still having the following problem when I try to get method argument hinting.

![image](https://user-images.githubusercontent.com/6594915/53225216-4454d680-36b2-11e9-8bc8-629783c5502d.png)
When I type the `(`, ST auto adds `)` and my cursor is in the mid of `()`, it tries to provide the method signature but then a python exception is thrown.

<details><summary>Click to show console error log</summary>

```
LSP:  --> textDocument/signatureHelp
LSP:      {'activeSignature': 0, 'signatures': [{'parameters': [{'documentation': {'kind': 'markdown', 'value': '_@param_ `int $op`  \nthe operation code'}, 'label': 'int $op'}], 'label': '(int $op)'}], 'activeParameter': 0}
Error handling server payload
Traceback (most recent call last):
  File "C:\Users\Clover\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/rpc.py", line 141, in receive_payload
    self.response_handler(payload)
  File "C:\Users\Clover\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/rpc.py", line 160, in response_handler
    handler(response["result"])
  File "C:\Users\Clover\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/signature_help.py", line 81, in <lambda>
    lambda response: self.handle_response(response, point))
  File "C:\Users\Clover\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/signature_help.py", line 103, in handle_response
    self._show_popup(point)
  File "C:\Users\Clover\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/signature_help.py", line 132, in _show_popup
    self._build_popup_content(),
  File "C:\Users\Clover\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/signature_help.py", line 152, in _build_popup_content
    return self._build_popup_content_style_vscode()
  File "C:\Users\Clover\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/signature_help.py", line 233, in _build_popup_content_style_vscode
    return "\n".join(formatted)
TypeError: sequence item 3: expected str instance, dict found
```

</details>

**Comment by rwols** [comment]
Maybe it's the value of the `documentation` key that's throwing things off? I seem to remember that we assume that `documentation` is always a `str`, but I may be wrong.

**Comment by carlevison** [comment]
@rwols You're correct it seems to be returning a ```dict```instead of a ```str````

Is this something that should be changed in LSP or Intelephense?

**Comment by jfcherng** [comment]
> @jfcherng What happens if you change the method so it isn't static? do you get signature help then?

Unfortunately nope. Thing like `$this->xxx()` would trigger an exception as well.
