### ISSUE TITLE
Setting LSP for sublime text 3 for clangd gives error

### ISSUE THREAD

**Issue by maxviv** [tomv564/LSP#534]
I am not able to make LSP work. Its giving some errors in console when the LSP is loaded
Details are below:

* OS 
Distributor ID: CentOS
Description:    CentOS release 6.6 (Final)
Release:        6.6
Codename:       Final

*  language server
LLVM (http://llvm.org/):
  LLVM version 5.0.2
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: broadwell

* How you installed LSP (Package Control or from git?)
I installed LSP through Package control

* Minimal reproduction steps
When I open sublime text 3 and see the console I find some errors

* Log
Error log from sublime text 3 console:
reloading plugin LSP.boot
Traceback (most recent call last):
  File "/depotbld/RHEL6.0/sublime_text_3/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/depotbld/RHEL6.0/sublime_text_3/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "boot in /remote/us01home57/vshaw/.config/sublime-text-3/Installed Packages/LSP.sublime-package", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/depotbld/RHEL6.0/sublime_text_3/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "plugin.rename in /remote/us01home57/vshaw/.config/sublime-text-3/Installed Packages/LSP.sublime-package", line 12, in <module>
AttributeError: 'module' object has no attribute 'TextInputHandler'

**Comment by jfcherng** [comment]
I am struggling with clangd LSP today as well and I finally make it work.

[Here's](https://github.com/jfcherng/my-Sublime-Text-ntoes/blob/master/cpp_lsp_tips.md) my detailed notes about the clangd LSP (for Ubuntu though).

A notable point for me is that there is a line in the [clangd](https://clang.llvm.org/extra/clangd/Installation.html#id2) installation guide which says:

```
You need a recent version of clangd: 7.0 was the first usable release, and 8.0 is much better.
```

`7.0` was the first "usable" release. I am not sure what the "usable" means but I install version 8 anyway.

**Comment by maxviv** [comment]
Thanks for the comments. But I think as per the log, I am getting the error while loading LSP.boot plugin.
Hence I am not getting any LSP options from command pallette

**Comment by tomv564** [comment]
@maxviv the error suggests that your Sublime Text is not exposing the `TextInputHandler` API, which is available in (regular) build 3170. What version do you have installed, and are you able to update?

**Comment by maxviv** [comment]
My ST build is 3143 and version is 3.0. I will try to update and check.

**Comment by maxviv** [comment]
Thanks @tomv564. Its working in build 3176
