### ISSUE TITLE
Autocompletion broken in master

### ISSUE THREAD

**Issue by LiteCatDev** [tomv564/LSP#582]
Using dart_language_server works in the version published in packagecontrol.io

However using the same server with the same configuration doesn't work with autocompletion at all 

console outputs this

> Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\LSP\plugin\core\rpc.py", line 152, in receive_payload
    self.response_handler(payload)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\LSP\plugin\core\rpc.py", line 171, in response_handler
    handler(response["result"])
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\LSP\plugin\completion.py", line 223, in handle_response
    self.completions = list(self.format_completion(item) for item in items)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\LSP\plugin\completion.py", line 223, in <genexpr>
    self.completions = list(self.format_completion(item) for item in items)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\LSP\plugin\completion.py", line 197, in format_completion
    return "\t  ".join((trigger, hint)) if hint else trigger, replacement
TypeError: sequence item 0: expected str instance, NoneType found

Gonna chek the commits to see which one of the 29 commits broke the autocompletion

**Comment by LiteCatDev** [comment]
Tracked back to this commit https://github.com/tomv564/LSP/commit/f4b4ce93ef9ef4da4ec97171fdcc6536b2c1aa3f#diff-ccb284e84187b2ce90d374d118bb2d9e , For some reason it breaks , i don't know python that well so i can't help , but using `"prefer_label_over_filter_text": true,` in the settings seems to be a fix

**Comment by rwols** [comment]
It looks like the dart language server has a `"filterText"` key, but it is set to `None`. We should check for that.

**Comment by rwols** [comment]
Let's keep this issue open until it is properly resolved.
