### ISSUE TITLE
Crash after view.sel().clear()

### ISSUE THREAD

**Issue by jgirardet** [tomv564/LSP#589]
Hi,
In my own plugin there is moment where I do  view.sel().clear(). If I let it empty I get the following error :
```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 478, in run_callback
    expr()
  File "/opt/sublime_text/sublime_plugin.py", line 499, in <lambda>
    run_callback(name, vel, lambda: vel.__class__.__dict__[name](vel))
  File "/home/jimmy/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/completion.py", line 199, in on_modified
    if self.view.sel()[0].begin() < self.last_location:
  File "/opt/sublime_text/sublime.py", line 649, in __getitem__
    raise IndexError()
IndexError
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 773, in on_post_text_command
    callback.on_post_text_command(v, name, args)
  File "/home/jimmy/.config/sublime-text-3/Packages/sublack/sublack/commands.py", line 155, in on_post_text_command
    view.show(view.line(view.sel()[0]))
  File "/opt/sublime_text/sublime.py", line 649, in __getitem__
    raise IndexError()
IndexError
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 506, in run_async_view_listener_callback
    vel.__class__.__dict__[name](vel)
  File "/home/jimmy/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/signature_help.py", line 73, in on_modified_async
    pos = self.view.sel()[0].begin()
  File "/opt/sublime_text/sublime.py", line 649, in __getitem__
    raise IndexError()
IndexError
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 506, in run_async_view_listener_callback
    vel.__class__.__dict__[name](vel)
  File "/home/jimmy/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/highlights.py", line 58, in on_selection_modified_async
    self._queue()
  File "/home/jimmy/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/highlights.py", line 67, in _queue
    current_point = self.view.sel()[0].begin()
  File "/opt/sublime_text/sublime.py", line 649, in __getitem__
    raise IndexError()
IndexError
```

I don't know if it's a bug with LSP  or if it's my fault. I fixed it in my plugin (I backup the previous sel() and reapply it before exiting my plugin stuff)

nice day

**Comment by tomv564** [comment]
LSP assumes there is no way for a user to have no cursor in a view, but I didn't notice a `clear()` function that would erase the last cursor programatically. 

For correctness's sake I guess LSP could introduce bounds checks everywhere, but what does Sublime Text do when a user interacts with a view after your plugin erases the selections? Immediately creates a new selection/cursor?

**Comment by jgirardet** [comment]
```
>>> view.sel().clear()
>>> view.sel()[0]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/sublime_text/sublime.py", line 649, in __getitem__
    raise IndexError()
IndexError
```
sublime does not auto correct it. it just does nothing. The problem problem is only if somebody wants to do anything with sel()

**Comment by tomv564** [comment]
Your solution of backing up and restoring the user's cursor sounds good 👍
