### ISSUE TITLE
RuntimeError when starting session

### ISSUE THREAD

**Issue by maddanio** [tomv564/LSP#682]
* OS and language server
osx 10.14.4
ccls version <unknown>
clang version 8.0.0 (tags/RELEASE_800/final)
ccls is from homebrew
* How you installed LSP (Package Control or from git?)
package control
* Minimal reproduction steps
work on a large c++ project with ccls lsp enabled for project based on cmake (with compile commands)
* Log
one crash:
```
Error handling server payload
Traceback (most recent call last):
  File "/Users/daniel/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/rpc.py", line 149, in receive_payload
    self.response_handler(payload)
  File "/Users/daniel/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/rpc.py", line 168, in response_handler
    handler(response["result"])
  File "/Users/daniel/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/sessions.py", line 141, in <lambda>
    lambda result: self._handle_initialize_result(result))
  File "/Users/daniel/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/sessions.py", line 147, in _handle_initialize_result
    self._on_created(self)
  File "/Users/daniel/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 387, in <lambda>
    lambda session: self._handle_session_started(session, project_path, config),
  File "/Users/daniel/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 482, in _handle_session_started
    self._documents.add_session(session)
  File "/Users/daniel/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 118, in add_session
    self._notify_open_documents(session)
  File "/Users/daniel/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 164, in _notify_open_documents
    for file_name in self._document_states:
RuntimeError: dictionary changed size during iteration
```

another:

```
Failure writing to stdout
Traceback (most recent call last):
  File "/Users/daniel/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/transports.py", line 227, in write_stdin
    self.process.stdin.flush()
OSError: [Errno 9] Bad file descriptor
```

**Comment by tomv564** [comment]
The first one looks like a race condition where more files are being opened/activated while we're still telling the server about the initial ones. We should probably copy the dict before iterating over it.

The second is hard to work with unless we have a matching failure from the server - from here it just looks like the server decided to exit abruptly.

Thanks for reporting!

**Comment by tomv564** [comment]
If you can capture any server output with further crashes of the 2nd type, please share them in a new issue!

**Comment by maddanio** [comment]
Will do. Will this change propagate directly through package control?

**Comment by tomv564** [comment]
No, a new release is needed which might take a few weeks
