### ISSUE TITLE
"Restart servers" option unnecessarily asks again to restart server

### ISSUE THREAD

**Issue by rchl** [tomv564/LSP#712]
Given that TS types are not reloaded when changing local types definitions (probably missing feature) I'm using "Restart servers" command a lot lately. That's sort of faster then restarting Sublime. But what slows me down a little bit is weird and IMO unnecessary behavior. After I invoke "Restart servers" command, I then need to:
 - do some edit on the file to trigger server initialization
 - get a dialog that server crashed and do I want to restart it
<img width="427" alt="server-crash" src="https://user-images.githubusercontent.com/153197/64711662-3fbf0680-d4ba-11e9-8cd9-cc5800be7de5.png">

Both those points are IMO unnecessary but at least the dialog triggering is a clear bug.

**Comment by tomv564** [comment]
Can you share logs where you get your servers started with a single document and then restart lsp-vue?

**Comment by rchl** [comment]
1. Trigger `Restart servers`:
```
LSP: unloading session lsp-vue
LSP:  --> shutdown
LSP:      None
Error handling server payload
Traceback (most recent call last):
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/core/rpc.py", line 149, in receive_payload
    self.response_handler(payload)
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/core/rpc.py", line 174, in response_handler
    error_handler(error)
TypeError: <lambda>() takes 0 positional arguments but 1 was given

LSP:  --> textDocument/didOpen
/Users/me/workspace/github/LSP-vue/node_modules/vue-language-server/dist/embeddedSupport/languageModes.js:78:
const mode = this.modes[lr.languageId];:
^:
:
TypeError: Cannot read property 'vue-html' of undefined:
at documentRegions.getAllLanguageRanges.forEach.lr (/Users/me/workspace/github/LSP-vue/node_modules/vue-language-server/dist/embeddedSupport/languageModes.js:78:36):
at Array.forEach (<anonymous>):
at LanguageModes.getAllLanguageModeRangesInDocument (/Users/me/workspace/github/LSP-vue/node_modules/vue-language-server/dist/embeddedSupport/languageModes.js:77:48):
at VLS.doValidate (/Users/me/workspace/github/LSP-vue/node_modules/vue-language-server/dist/services/vls.js:356:32):
at VLS.validateTextDocument (/Users/me/workspace/github/LSP-vue/node_modules/vue-language-server/dist/services/vls.js:350:34):
at Timeout.pendingValidationRequests.(anonymous function).setTimeout [as _onTimeout] (/Users/me/workspace/github/LSP-vue/node_modules/vue-language-server/dist/services/vls.js:339:18):
at ontimeout (timers.js:436:11):
at tryOnTimeout (timers.js:300:5):
at listOnTimeout (timers.js:263:5):
at Timer.processTimers (timers.js:223:10):
LSP: LSP stream logger stopped.
LSP: process 15623 stdout ended (still alive)
LSP: process 15623 exited with code 1
```

2. Make and edit in the document:
```
LSP:  --> textDocument/didChange
Failure writing to stdout
Traceback (most recent call last):
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/core/transports.py", line 232, in write_stdin
    self.process.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe

LSP: transport failed
LSP: no session found
LSP: unloading session lsp-vue
LSP: unable to send shutdown
LSP: unable to send exit
LSP: window 15 requests lsp-vue for /Users/me/workspace/npm-packages/tidal-styles-content/src/components/tidal-content-cta.vue
LSP: session lsp-vue ended
LSP: clients for window 15 unloaded
LSP: window 15 sessions unloaded - restarting
LSP: starting in /Users/me/workspace/npm-packages/tidal-styles-content
LSP: window 15 starting 1 initial views
LSP: starting ['node', '/Users/me/Library/Application Support/Sublime Text 3/Packages/LSP-vue/node_modules/vue-language-server/bin/vls']
LSP:  --> initialize
LSP: window 15 added session lsp-vue
lsp-vue: Failed to load typescript from workspace. Using bundled typescript@3.6.2.
lsp-vue: Vetur initialized
LSP:      {'capabilities': {'codeActionProvider': True, 'referencesProvider': True, 'documentLinkProvider': {'resolveProvider': False}, 'signatureHelpProvider': {'triggerCharacters': ['(']}, 'definitionProvider': True, 'colorProvider': True, 'documentHighlightProvider': True, 'documentFormattingProvider': False, 'textDocumentSync': 1, 'documentSymbolProvider': True, 'completionProvider': {'resolveProvider': True, 'triggerCharacters': ['.', ':', '<', '"', "'", '/', '@', '*']}, 'hoverProvider': True}}
LSP:  --> initialized
LSP:  --> textDocument/didOpen
```
