### ISSUE TITLE
ValueError: path is on mount 'D:', start on mount 'C:'

### ISSUE THREAD

**Issue by AmjadHD** [tomv564/LSP#727]
* OS: Windows 10
* How you installed LSP (Package Control or from git?): git (latest master be60102fdf8b72de85fe1088eafbd248516ef6f9)
* Minimal reproduction steps
1. open a project with two folders one in C drive and the other in D:
'''json
{
	"folders":
	[
		{
			"path": "C:\\Users\\Lehdhili\\AppData\\Roaming\\Sublime Text 3\\Packages\\LSP-rust"
		},
		{
			"path": "D:\\Amjad\\rls-vscode"
		}
	]
}```
2. open a file in the D folder
3. invoke references on a name in that file
* Log
```
LSP:  --> textDocument/references
LSP:      [{'uri': 'file:///D:/Amjad/rls-vscode/src/extension.ts', 'range': {'end': {'line': 25, 'character': 20}, 'start': {'line': 25, 'character': 9}}}, {'uri': 'file:///D:/Amjad/rls-vscode/src/extension.ts', 'range': {'end': {'line': 434, 'character': 25}, 'start': {'line': 434, 'character': 14}}}, {'uri': 'file:///D:/Amjad/rls-vscode/src/rustup.ts', 'range': {'end': {'line': 67, 'character': 33}, 'start': {'line': 67, 'character': 22}}}]
Error handling server payload
Traceback (most recent call last):
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\LSP\plugin\core\rpc.py", line 150, in receive_payload
    self.response_handler(payload)
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\LSP\plugin\core\rpc.py", line 169, in response_handler
    handler(response["result"])
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\LSP\plugin\references.py", line 45, in <lambda>
    request, lambda response: self.handle_response(response, pos))
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\LSP\plugin\references.py", line 64, in handle_response
    formatted_references = self._get_formatted_references(response, base_dir)
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\LSP\plugin\references.py", line 142, in _get_formatted_references
    grouped_references = self._group_references_by_file(references, base_dir)
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\LSP\plugin\references.py", line 150, in _group_references_by_file
    relative_file_path = os.path.relpath(file_path, base_dir)
  File "./python3.3/ntpath.py", line 564, in relpath
ValueError: path is on mount 'D:', start on mount 'C:'
```
possible duplicate #247

**Comment by tomv564** [comment]
Looks like a check for `os.path.commonprefix` went missing, but adding it in now will make the references behaviour really inconsistent. I'd prefer to leave this bug in place until we build better support for multiple workspace folders.
