### ISSUE TITLE
ValueError: path is on mount 'D:', start on mount 'C:' again

### ISSUE THREAD

**Issue by AmjadHD** [tomv564/LSP#815]
Please include in your report:

* OS: Windows 10
* How you installed LSP: git (latest)
* Minimal reproduction steps
1. Open a project folder located under C:/
2. open a file located under D:/
* Log
```
Error handling notification textDocument/publishDiagnostics
Traceback (most recent call last):
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\LSP\plugin\core\rpc.py", line 236, in handle
    handler(params, *args)
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\LSP\plugin\core\windows.py", line 543, in <lambda>
    lambda params: self.diagnostics.receive(session.config.name, params))
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\LSP\plugin\core\diagnostics.py", line 71, in receive
    self._notify(file_path, client_name)
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\LSP\plugin\core\diagnostics.py", line 77, in _notify
    self._updatable.update(file_path, client_name, self._diagnostics)
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\LSP\plugin\diagnostics.py", line 416, in update
    walker.walk(diagnostics)
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\LSP\plugin\core\diagnostics.py", line 320, in walk
    self.invoke_each(lambda w: w.end_file(file_path))
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\LSP\plugin\core\diagnostics.py", line 326, in invoke_each
    func(sub)
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\LSP\plugin\core\diagnostics.py", line 320, in <lambda>
    self.invoke_each(lambda w: w.end_file(file_path))
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\LSP\plugin\diagnostics.py", line 339, in end_file
    panel_file_path = os.path.relpath(file_path, self._base_dir) if self._base_dir else file_path
  File "./python3.3/ntpath.py", line 564, in relpath
ValueError: path is on mount 'D:', start on mount 'C:'
```

**Comment by rwols** [comment]
Feels like we should do exactly this https://github.com/SublimeLinter/SublimeLinter/pull/1658

**Comment by tomv564** [comment]
I think #809 will fix this

**Comment by tomv564** [comment]
multi-folder support now merged, issue should be solved.
