### ISSUE TITLE
Should we notify workspace/didChangeWorkspaceFolders when nothing has changed?

### ISSUE THREAD

**Issue by rwols** [tomv564/LSP#830]
I'm not sure if it's correct to notify workspace/didChangeWorkspaceFolders when nothing has changed. At least, pyls seems to throw a fit about it:

```
:: --> pyls workspace/didChangeWorkspaceFolders: {'event': {'removed': [], 'added': []}}
pyls: 2019-12-19 18:50:04,738 UTC - ERROR - pyls_jsonrpc.endpoint - Failed to handle notification workspace/didChangeWorkspaceFolders: {'event': {'removed': [], 'added': []}}
:: --> pyls textDocument/didOpen
pyls: Traceback (most recent call last):
pyls: File "/usr/local/lib/python3.7/site-packages/pyls_jsonrpc/endpoint.py", line 142, in _handle_notification
pyls: handler_result = handler(params)
pyls: File "/usr/local/lib/python3.7/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
pyls: return method(**(params or {}))
pyls: File "/usr/local/lib/python3.7/site-packages/pyls/python_ls.py", line 363, in m_workspace__did_change_workspace_folders
pyls: for removed_info in removed:
pyls: TypeError: 'NoneType' object is not iterable
```

These are the workspace folders I start out with in my local LSP.sublime-project (from the initialize request)

```
'workspaceFolders': [{'uri': 'file:///Users/raoulwols/Library/Application%20Support/Sublime%20Text%203/Packages/LSP-eslint', 'name': 'LSP-eslint'}, {'uri': 'file:///Users/raoulwols/Library/Application%20Support/Sublime%20Text%203/Packages/LSP', 'name': 'LSP'}, {'uri': 'file:///Users/raoulwols/Library/Application%20Support/Sublime%20Text%203/Packages/LSP/Docs', 'name': 'Docs'}, {'uri': 'file:///Users/raoulwols/Library/Application%20Support/Sublime%20Text%203/Packages/LSP/Menus', 'name': 'Menus'}]
```

Perhaps another thing of note: the rootUri seems to be the *last* WorkspaceFolder in my list of folders, shouldn't it be the first?

```
'rootUri': 'file:///Users/raoulwols/Library/Application%20Support/Sublime%20Text%203/Packages/LSP-eslint'
```

Here's a copy of my LSP.sublime-project file:
```
{
	"folders":
	[
		{
			"path": "."
		},
		{
			"name": "documentation",
			"path": "Docs"
		},
		{
			"path": "Menus"
		},
		{
			"path": "../LSP-eslint"
		}
	]
}
```

**Comment by tomv564** [comment]
Looks like a bug from our side to send an empty list, in which sequence did you open files belonging to which folders ( so I can repro)?

Didn't know pyls supported it either, but how can it get a None out of an empty list in `for removed_info in removed:`?
